### ISSUE TITLE
[HLS] Duration of variable playlists does not match

### ISSUE THREAD

**Issue by chriswiggins** [sergey-dryabzhinsky/nginx-rtmp-module#101]
Hi all,

Glad that someone has continued the nginx rtmp module - I use it a lot for projects and it works great.

I'm noticing that on live playlists with a large playlist length (i.e 60 mins) that some weird things happen. I use a large playlist size to offer "DVR" functionality

1. The length of the playlist / number of segments is greater than the set amount? I have the playlist set at 60 mins however one playlist length is 120 mins and the other is ~90mins. This causes issues with players trying to play the variants as they get confused
2. I've got my keyframe interval the same as the framerate, however each segment isn't split on the exact `hls_fragment` value. The 100kbps stream is fine, but the 500kbps is split every 1.467 seconds??
2. HLS playlists take ages to start playing on an iOS device - for comparison, Wowza HLS streams load almost instantly. I note that the Wowza playlists include the codec information and resolution but we don't in this module. Would that cause it at all?
3. This module still puts audio headers in TS files if there is no audio present. Is that hard to fix? Using `meta copy` fixes it on the RTMP feed but not with the MPEG-TS files

Conf file:
```
user www-data;
worker_processes 1;
pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}


rtmp {

	server {

		listen 1935;
		application camera {

			# enable live streaming
			live on;
			wait_video on;
			meta copy;

			interleave on;

			allow publish all;

			allow play all;

			hls on;
			hls_path /var/ramdisk/hls/camera;
			hls_fragment 1;
			hls_fragment_slicing plain;
			hls_type live;
			hls_playlist_length 60m;
			hls_continuous off;
			hls_nested on;


			#bandwidth is in bps
			hls_variant _hi BANDWIDTH=500000;
			hls_variant _lo BANDWIDTH=100000;


		}
	}
}

http {

	server {

		listen 8081;

		location /hls {
			# Serve HLS fragments
			types {
				application/vnd.apple.mpegurl m3u8;
				video/mp2t ts;
			}
			alias /var/ramdisk/hls;
			add_header Cache-Control no-cache;
		}

		location /crossdomain.xml {
			root /opt/misc/hls;
		}
	}
}
```

Appreciate any help!

**Comment by yverbin** [comment]
Disable scenecut or its equivalent parameter in your encoder

**Comment by chriswiggins** [comment]
@yverbin I've tried `-x264opts keyint=15:scenecut=-1`  on the ffmpeg command line but that doesn't help. Any ideas?

**Comment by yverbin** [comment]
show me, please, the full ffmpeg command string. Also, different length of playlists may result of network issues, known problems in ffmpeg, when its working as publisher with remote rtmp server, and server performance problems. But in your case, difference between playlists are very large for any kind of the above problems

**Comment by JIEgOKOJI** [comment]
Lol set fragment more than 1 sec. And set keyfraime interval less than fragment size. And go to read specs and docs of nginx-rtmp

**Comment by chriswiggins** [comment]
OK. So here's the outcomes:
1. Still not sure (maybe I've fixed it with the fix for 2)
2. Setting ffmpeg to `-vsync 1` sorts this
3 & 4: See #106
