### ISSUE TITLE
rtmp { }  – Segmentation fault

### ISSUE THREAD

**Issue by denji** [sergey-dryabzhinsky/nginx-rtmp-module#103]
https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/commit/9f75cc2c6e5d7f156a8d972e947f4b6c285d8551 /etc/nginx/nginx.conf
---
```nginx
load_module modules/ngx_rtmp_module.so;

user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events { worker_connections 1024; }
# http { }
rtmp { }
```

# nginx -t
Segmentation fault

# nginx -V
nginx version: nginx/1.9.14
built by gcc 4.7.2 (Debian 4.7.2-5)
built with OpenSSL 1.0.1e 11 Feb 2013
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_perl_module=dynamic --add-dynamic-module=debian/extra/njs-91543c86f412/nginx --with-threads --with-stream --with-stream_ssl_module --with-http_slice_module --with-mail --with-mail_ssl_module --with-file-aio --with-http_v2_module --with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,--as-needed' --with-ipv6

# lsb_release -d
Description:	Debian GNU/Linux 7.10 (wheezy)

**Comment by misiek08** [comment]
It was mentioned long time ago, module's behaviour with empty rtmp block is undefined and can lead to crash.

**Comment by denji** [comment]
```nginx
rtmp {
    server {
        listen 1935;
        application live {
            live on;
        }
    }
}
```

# nginx -t
Segmentation fault

**Comment by denji** [comment]
[`sergey-dryabzhinsky/nginx-rtmp-module@9f75cc2:ngx_rtmp_record_module.c#L521-L535`](https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/blob/9f75cc2c6e5d7f156a8d972e947f4b6c285d8551/ngx_rtmp_record_module.c#L521-L535)
[ngx_rtmp_record_module.c:521] -> [ngx_rtmp_record_module.c:535]: (performance) Variable 'file_size' is reassigned a value before the old one has been used.

[`sergey-dryabzhinsky/nginx-rtmp-module@9f75cc2:ngx_rtmp_relay_module.c#L360-L361`](https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/blob/9f75cc2c6e5d7f156a8d972e947f4b6c285d8551/ngx_rtmp_relay_module.c#L360-L361)
[ngx_rtmp_relay_module.c:360] -> [ngx_rtmp_relay_module.c:361]: (performance) Variable 'pool' is reassigned a value before the old one has been used.

**Comment by misiek08** [comment]
Those should be warning only and they are not connected with segmentation fault.

**Comment by sergey-dryabzhinsky** [comment]
Try latest master after #104
