### ISSUE TITLE
add-publisher-redirect-support make error

### ISSUE THREAD

**Issue by zhxiaom5** [sergey-dryabzhinsky/nginx-rtmp-module#110]
when i build add-publisher-redirect-support,the error below show
with  nginx-1.8.1

../../nginx-rtmp-module/ngx_rtmp_notify_module.c: In function ‘ngx_rtmp_notify_publish_handle’:
../../nginx-rtmp-module/ngx_rtmp_notify_module.c:1164: error: too few arguments to function ‘ngx_rtmp_send_close_method’
make[1]: *** [objs/addon/nginx-rtmp-module/ngx_rtmp_notify_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/dist/nginx_rtmp/nginx-1.8.1'
make: *** [build] Error 2

thinks

**Comment by zhxiaom5** [comment]
send = ngx_rtmp_send_close_method(s);
change to 
send = ngx_rtmp_send_close_method(s,"close")
the error disappeared

**Comment by sergey-dryabzhinsky** [comment]
You should not build it. This branch is merged into master already.
