### ISSUE TITLE
Integration of travis-ci and automation ideas

### ISSUE THREAD

**Issue by denji** [sergey-dryabzhinsky/nginx-rtmp-module#120]
#### The idea:
- [ ] valgrind, cppcheck, gdb, [Coverity Scan](https://scan.coverity.com/)
- [ ] Deploy deb/rpm with dynamic linking `ngx_rtmp_module.so`
  - [ ] Attach the dynamic modules version `ngx_rtmp_module-([major].[minor]).[tar.gz|zip]`
- [ ] [Unified code style to simplify and improve code-readability](http://nginx.org/en/docs/contributing_changes.html#formatting_changes)
#### Sanitizer (Address/Thread/Memory/UndefinedBehavior/DataFlow)—Sanitizer
- https://github.com/arsenm/sanitizers-cmake
- [Controlling Code Generation](http://clang.llvm.org/docs/UsersManual.html#controlling-code-generation)  [`Basic/Sanitizers`](http://llvm.org/svn/llvm-project/cfe/trunk/include/clang/Basic/Sanitizers.def)
- Ubuntu/Debian official repo: http://llvm.org/apt/
#### Fuzzing
- http://lcamtuf.coredump.cx/afl/ (  https://github.com/stribika/afl-fuzz )
  - https://github.com/rc0r/afl-utils
- http://caca.zoy.org/wiki/zzuf ( https://github.com/samhocevar/zzuf ) - multi-purpose fuzzer
- http://llvm.org/docs/LibFuzzer.html
- https://github.com/google/honggfuzz
- https://fuzzing-project.org/tutorials.html
#### Multi-threaded profiling
- [Coz: Causal Profiling](https://github.com/plasma-umass/coz)
  - [Coz: Finding Code that Counts with Causal Profiling - An Introduction](http://mattwarren.github.io/2016/03/30/Coz-Finding-Code-that-Counts-with-Causal-Profiling/)
    - [Interactive Viewer Causal Profile](http://plasma-umass.github.io/coz/)
  - http://dl.acm.org/citation.cfm?doid=2815400.2815409
  - http://sigops.org/sosp/sosp15/current/2015-Monterey/printable/090-curtsinger.pdf
  - http://www.cs.grinnell.edu/~curtsinger/files/coz_slides.pdf
### Analyze `#includes` in C and C++ source files
- [deheader](http://www.catb.org/~esr/deheader/)
- [include-what-you-use](https://github.com/include-what-you-use/include-what-you-use/)
  - http://llvm.org/devmtg/2010-11/Silverstein-IncludeWhatYouUse.pdf
  - https://blog.mozilla.org/nnethercote/2013/08/13/using-include-what-you-use/
- [find-unnecessary-includes](https://github.com/pukkaone/find-unnecessary-includes)
#### Refs
- https://github.com/TrustInSoft/tis-interpreter
- http://astyle.sourceforge.net/
- http://clang.llvm.org/docs/ClangFormat.html
- http://uncrustify.sourceforge.net/
- https://github.com/oclint/oclint
- http://clang.llvm.org/docs/ClangFormat.html
- http://clang.llvm.org/extra/clang-tidy/index.html
- https://github.com/DynamoRIO/drmemory
- https://github.com/DynamoRIO/dynamorio

**Comment by chriswiggins** [comment]
We could also potentially have ffmpeg threads fire up and ensure that they can connect, publish, and also test HLS/DASH segments in a whole lot of ways.
