### ISSUE TITLE
[hls] EXT-X-PROGRAM-DATE-TIME Status

### ISSUE THREAD

**Issue by RLovelett** [sergey-dryabzhinsky/nginx-rtmp-module#125]
What is the status of the [`EXT-X-PROGRAM-DATE-TIME`](https://tools.ietf.org/html/draft-pantos-http-live-streaming-13#section-3.4.5) tag in this fork?

Issue #42 seems to indicate that it is available but not working. Forgive me but I cannot seem to figure out how to enable the flag.

My configuration looks like so:

```
application hls {
  live on;
  hls on;
  hls_path /tmp/hls;
  hls_fragment_naming system;
  hls_fragment 6s;
  hls_playlist_length 120m;
  allow publish 127.0.0.1;
}
```

**Comment by sergey-dryabzhinsky** [comment]
Try set ```hls_datetime system;```.

**Comment by RLovelett** [comment]
That did the trick. Thank you.

**Comment by paramaggarwal** [comment]
We need to document this.

**Comment by ctaity** [comment]
I put hls_datetime system;  My config:

application hls-video {
            live on; # Allows live input from above
            hls on; # Enable HTTP Live Streaming
            hls_nested on;
            hls_path /mnt/disk2/hls/video;
            hls_fragment 4s;
            hls_playlist_length 60m;
            hls_continuous on;
            hls_cleanup on;
            hls_fragment_naming system;
            hls_fragment_naming_granularity 1000;
            #hls_fragment_slicing aligned;
            hls_type live;
            hls_allow_client_cache disabled;
            hls_datetime system;        #https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/issues/125
            hls_keys on;
            hls_key_path /mnt/disk2/keys/video;
            hls_key_url https://vody-auth.tvpublica.com.ar/server01/;
            hls_fragments_per_key 60;


            hls_variant _240 RESOLUTION=320x240 BANDWIDTH=500000; # Low bitrate, sub-SD resolution
            hls_variant _360 RESOLUTION=480x360 BANDWIDTH=1000000; # Low bitrate, sub-SD resolution
            hls_variant _480 RESOLUTION=854x480 BANDWIDTH=2000000; # High bitrate, higher-than-SD resolution
            hls_variant _720 RESOLUTION=1280x720 BANDWIDTH=3000000; # Source bitrate, source resolution
            hls_variant _1080 RESOLUTION=1920x1080 BANDWIDTH=4000000; # Source bitrate, source resolution
        }


but in the m3u8 file dont appear  EXT-X-PROGRAM-DATE-TIME tag.

Thanks
