### ISSUE TITLE
Error when build docker container with rtmp-module

### ISSUE THREAD

**Issue by agiUnderground** [sergey-dryabzhinsky/nginx-rtmp-module#151]
File contain an error description. Error in 'ngx_rtmp_core_listen' function and other.
[error.txt](https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/files/312630/error.txt)

**Comment by sergey-dryabzhinsky** [comment]
You are using 1.11 nginx sources? I so - use latest code from ```dev``` branch.

**Comment by agiUnderground** [comment]
@sergey-dryabzhinsky Yes, i use 1.11.1 from default branch from here - http://hg.nginx.org/nginx/ 
And i can not find dev brunch. Can you help me please with this, how to clone dev brunch?

**Comment by agiUnderground** [comment]
Ok, i compile with dev version of module, all good!
