### ISSUE TITLE
 [error] hls: force fragment split

### ISSUE THREAD

**Issue by dodolzg** [sergey-dryabzhinsky/nginx-rtmp-module#152]
When I push the rtmp audio stream, it shows error log:
> 2016/06/14 17:20:28 [error] 2047#0: *87110 hls: force fragment split: 10.031 sec, , client: 192.168.1.82, server: 0.0.0.0:1935

Here is my config:
```
                application dev_hls {
                        live on;
                        hls on;
                        hls_path /data/cdn/dev/hls;
                        hls_nested on;
                        hls_fragment 10s;
                        hls_playlist_length 36000s;
                        hls_cleanup off;
                        drop_idle_publisher 10s;
                }
```
The version is master branch, and arut/nginx-rtmp-module 1.1.7, it works fine.

**Comment by karlisk** [comment]
I noticed the same issue, issue is present when using nginx-1.10.1 and nginx-1.11.1 with nginx-rtmp-module-dev, also noticed some stuttering for HLS in-between *.ts segments. I'll fiddle around with different versions and see when it appears as well as bring some debug logs to help pinpoint the source of the problem.

**Comment by karlisk** [comment]
In my situation it seems that setting `hls_fragment` to 3 seconds (according to documentation default is 5) seems to fix this.

**Comment by sergey-dryabzhinsky** [comment]
I think that you need to set in video encoder ```key_frame_interval``` or ```GOP``` to about 10 second. So it will split fragments like that.
If you need to split in smaller than ```10s``` chunks - set GOP to ```1 sec```.
But precision will be worse.

**Comment by dodolzg** [comment]
@sergey-dryabzhinsky Sorry, I forgot to mention that there is  only audio in my stream.
I try to config key_frame_interval or GOP in file:

> application dev_hls {
live on;
hls on;
hls_path /data/cdn/dev/hls;
hls_nested on;
hls_fragment 10s;
hls_playlist_length 36000s;
hls_cleanup off;
drop_idle_publisher 10s;
key_frame_interval 10s;
}

or

> application dev_hls {
live on;
hls on;
hls_path /data/cdn/dev/hls;
hls_nested on;
hls_fragment 10s;
hls_playlist_length 36000s;
hls_cleanup off;
drop_idle_publisher 10s;
GOP 10s;
}

It comes error:

> nginx: [emerg] unknown directive "key_frame_interval" in /usr/local/nginx/conf/nginx.conf:134
nginx: [emerg] unknown directive "GOP" in /usr/local/nginx/conf/nginx.conf:135
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed

**Comment by sergey-dryabzhinsky** [comment]
No, it was not about nginx-rtmp params but your encoder params.
FFmpeg, FMLE etc.

**Comment by dodolzg** [comment]
Sorry for mistake.
In this case. both the ts file and mp3 that processed by ffmpeg work fine although there is error log. 
I am just confused how to avoid the error.

**Comment by sergey-dryabzhinsky** [comment]
Oh, there is an error but in documentation:
1. ```hls_fragment``` is ```5s``` by default.
2. ```hls_max_fragment``` not documented and equals ```hls_fragment * 2```.

And this error on log (should be warning) occurs then writed fragment is more then ```hls_max_fragment``` length.
Try to avoid this by:
1. set ```hls_fragment``` to reasonable length
2. set ```hls_max_fragment``` to twice length by force
3. set in encoder GOP/key_frame_interval by half of ```hls_fragment``` or equal to it.

**Comment by karlisk** [comment]
Is there any detailed documentation for GOP available somewhere? In my situation, I'm using vMix for streaming with streaming parameters as follow: 1280x720p @ 25fps, keyframe every 3sec, x264 profile Main 3.1 and video bitrate of 2.0Mbit/s.

**Comment by matiaspl** [comment]
Your GOP (keyframe interval) equals 3 seconds.

Matt
20 cze 2016 14:40 "Kārlis K." <notifications@github.com> napisał(a):

**Comment by dodolzg** [comment]
@sergey-dryabzhinsky Thanks for your advice, it works.

**Comment by toshic** [comment]
I think `hls_max_fragment` is calculated incorretly. It's calculated from the first level of config it could be present, and if `hls_fragment` is not specified it's value is 5. So, if you specify `hls_fragment 10;` inside the app section, `hls_max_fragment` will be nested from srv section and it's value will be also 10.

**Comment by sergey-dryabzhinsky** [comment]
@toshic Or maybe it must be mentioned in docs that `hls_max_fragment` must be defined with `hls_fragment` on the same level of config.

**Comment by mkrn** [comment]
@sergey-dryabzhinsky 

Getting this error on repeat loop and nginx (single worker) goes to 100% CPU, cannot recover. Any ideas? 

```
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: -16.860 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: 16.894 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: -16.847 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: 16.880 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: -16.857 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: 16.890 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: -16.843 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: 16.877 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: -16.854 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: 16.887 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: -16.841 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: 16.874 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: -16.851 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: 16.885 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: -16.861 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: 16.894 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: -16.871 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: 16.904 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: -16.858 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: 16.892 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: -16.868 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: 16.901 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
2020/10/17 23:44:31 [error] 1359#0: *62461 hls: force fragment split: -16.855 sec, , client: 127.0.0.1, server: 0.0.0.0:1935
```
