### ISSUE TITLE
Cannot use include to specify a rtmp.conf file

### ISSUE THREAD

**Issue by MacKirby** [sergey-dryabzhinsky/nginx-rtmp-module#153]
I'm going to be running multiple nginx-rtmp servers in different locations, and I want to rsync an rtmp.conf file that specifies the rtmp block.  if I do this, the nginx server no longer listens on the specified port (1935).  Is it not possible to use the `include` statement in the nginx.conf file to specify a separate config for the rtmp stuff?

Note: If I specify the rtmp block in the main config files, everything works fine, but that is not suitable for my use case.

**Comment by RocFang** [comment]
I have tried config files below:

```

worker_processes  1;

error_log  logs/error.log  error;

events {
    worker_connections  1024;
}

include "../rtmp.conf";
include "../http.conf";

```
And worked fine.

**Comment by MacKirby** [comment]
Using your example, I managed to figure out what was going wrong - I was expecting to be able to use the `include` statement inside the `http{}` block for this.  Adding a new `include` statement before that block has solved things.
