### ISSUE TITLE
DASH: MPD must have par if sar is present

### ISSUE THREAD

**Issue by ReubenM** [sergey-dryabzhinsky/nginx-rtmp-module#170]
The generated mpd files are failing to pass the validation ( http://www-itec.uni-klu.ac.at/dash/?page_id=605 ) due to sar being present in the Representation without a corresponding par being present in the AdaptationSet.

I believe the logic is that if you have multiple spatial representations where one of the lower res representations is SD, it will likely have the goofy SAR that SD broadcast resolutions have, and it wants the par attribute available in order to be able to validate it.

Not really a show-stopper ;) but would be nice to have it validate against the official validation tool.

**Comment by sergey-dryabzhinsky** [comment]
Please check latest code from ```add-par-to-sar``` branch.

And I think that validator - http://dashif.org/conformance.html - has latest scheme support.
ITEC doesn't like `UTCTiming` tag.

**Comment by ReubenM** [comment]
Looks good to me. I vote pull it into the dev branch.

**Comment by sergey-dryabzhinsky** [comment]
Merged into `dev`
