### ISSUE TITLE
nclients value doesn't count DASH viewers

### ISSUE THREAD

**Issue by frutality** [sergey-dryabzhinsky/nginx-rtmp-module#177]
Hello.

Trying to get number of clients watching current stream. Using /stat location of course.

If user watch the stream with JWPlayer, he counts as a client. Everything is ok. But if user watch the stream with shaka-player (currently using https://cdnjs.com/libraries/shaka-player/2.0.0-beta3), he is not in client list. 

/stat tells me there is only 1 client (streamer himself).

---

BTW, is there recommended nginx configuration and recommended players for DASH and HLS? At this moment I'm using default config from tutorial and haven't try HLS, but DASH works not very well. Flash works fine, but you know — everybody wants crossbrowserability.

**Comment by sergey-dryabzhinsky** [comment]
DASH/HLS clients use generic nginx http module. nginx-rtmp module don't counting them.

You can try ```dev``` branch. It has some testing fixes for HLS/DASH playlist generation.

**Comment by matiaspl** [comment]
I use a simple netstat + grep script counting the number of client IP
addresses that keep open http connections to my HLS servers. This gives a
rough approximate of current viewers count (a few clients behind the same
NAT are treated as one, so it's a bit underestimated).
And Cacti for pretty graphs for multiple servers.

Matt

7 sie 2016 14:30 "frutality" <notifications@github.com> napisał(a):

**Comment by frutality** [comment]
Thanks guys. I was thinking and trying some ways, and in my case simplest way is just count online users at stream page. It's not accurate since somebody could watch stream with VLC or other software, but most people in my case would use browser.
