### ISSUE TITLE
Parameters with PHP scripts and OBS? (Question)

### ISSUE THREAD

**Issue by MacKirby** [sergey-dryabzhinsky/nginx-rtmp-module#179]
So I have a PHP script running on a web server, and it works fine.  It looks for a `username` and `pass` from the `Play Path/Stream key` in OBS, for example:

`live?username=usernamehere&pass=passwordhere`

The issue with this setup is that it allows anyone with a valid username and password to stream to any application.  I want to force the PHP script to specify the `username` like this:

`on_publish http://domain.name/script.php?username=usernamehere;`

And then specify only the `pass` in the `Play Path/Stream key` in OBS, like this:

`live&pass=passwordhere`

Am I simply messing up syntax or is it outwith the realms of possibility?

**Comment by chriswiggins** [comment]
Why don't you just use a different variable for the username, and ignore the one that nginx sends through? I.e use "user_name=usernamehere"

Does that help?

On 9/08/2016, at 6:29 AM, MacKirby <notifications@github.com<mailto:notifications@github.com>> wrote:


So I have a PHP script running on a web server, and it works fine. It looks for a username and pass from the Play Path/Stream key in OBS. The issue with this setup is that it allows anyone with a valid username and password to stream to any application. I want to force the PHP script to specify the username like this:

on_publish http://domain.name/script.php?username=usernamehere

And then specify only the pass in the Play Path/Stream key in OBS, like this:

live&pass=randompasswordhere

Am I simply messing up syntax or is it outwith the realms of possibility?

-

**Comment by MacKirby** [comment]
A friend of mine pointed out that you can grab $app via $_POST, so I should be able to add a check for that in the PHP script, which solves my problem.
