### ISSUE TITLE
Is it possible to maintain push after service reload?

### ISSUE THREAD

**Issue by MacKirby** [sergey-dryabzhinsky/nginx-rtmp-module#180]
My nginx-rtmp setup involves 4 servers - 3 ingests, and 1 "node" server that serves live video.  When a config file is modified, I have `incron` set to reload nginx.  Currently the issue is that reloading the "node" server causes the `push`es from the ingest servers to drop.  

Is there any way around this behaviour?

**Comment by ReubenM** [comment]
No. Unlike http, rtmp is a stateful protocol and that state is contained in the child processes that get killed when the nginx master process does a reload. See #155
