### ISSUE TITLE
Multiple streams, only some with Transcoding

### ISSUE THREAD

**Issue by nik736** [sergey-dryabzhinsky/nginx-rtmp-module#181]
Hi guys,

thanks for this fork. I just have a question how to handle multiple streams with different requirements. For example I have hundreds of different streams but only a handful of them need transcoding. I can see that I can use exec to start the ffmpeg transcoding process, but I only need it for some streams and not for all. 

What's the best way to tell nginx rtmp to only transcode the streams with a specific name? The transcodings are also not always the same, for some users it will be only one transcoding, for another stream I need multiple transcodings. Is this possible to handle with nginx rtmp?

Thanks for any help!! :-)

**Comment by sergey-dryabzhinsky** [comment]
If transcoding is dynamic and depends on something then nginx don't know what to do.
You should write a transcoding service that have some API. And you send commands to it.

**Comment by chriswiggins** [comment]
As per what @sergey-dryabzhinsky says, make a backend script that decides what to do with incoming streams. You can use the on_notify scripts to respond with redirects to nginx which could help you with what you want

**Comment by ReubenM** [comment]
> What's the best way to tell nginx rtmp to only transcode the streams with a specific name? 

You can do it directly if it is based entirely by name. If you have a stream named "foo" and you always want to transcode foo using the same settings you can set a directive:

```exec_push ffmpeg -blah -blah name=foo;```

and that will only call ffmpeg when the name matches foo. Don't do something silly like setting ffmpeg to republish the transcoded stream back to the the same stream name.

**Comment by nik736** [comment]
Thanks guys.

My problem is that the transcodings can change, one day its only 2 transcodings, the next it's 4, the other day it's none. I could write something that changes the nginx config and the exec push line for that "name". 

The problem is that I read that nginx-reload isn't working and I don't want to restart the server every time the transcodings change, because than the active streams will disconnect. Is there any other option?

Any suggestions?

If I write a transcoding service I think I can't use the hls_variant option (?) How do I combine them during the transcoding process if it's a livestream and HLS?

Thanks!

**Comment by ReubenM** [comment]
Dynamic transcoding shouldn't be managed by nginx. Instead, set up an external framework (script, service, etc) to manage calling ffmpeg to pull, transcode or transmux, and re-publish streams in whatever way you direct it to. You shouldn't ever need to restart or even reload nginx. I might recommend setting up a small web app hosted by nginx that manages transcoding by calling ffmpeg based up info in JSON requests it receives.

**Comment by karlisk** [comment]
Not sure about your set-up but you could have two applications - one that doesn't do transcoding and another that does.

**Comment by nik736** [comment]
Thanks Kārlis, the problem is that my channels don't have the same amount of transcodings and it varies a lot from day to day. So I just finished coding a transcoding service now, so I am completely flexible.

Thanks for all your answers.
