### ISSUE TITLE
HLS audio fine - DASH no audio

### ISSUE THREAD

**Issue by TheStripe** [sergey-dryabzhinsky/nginx-rtmp-module#186]
Hi. trying to debug why my dash stream has no audio but my hls stream does. I am compiling nginx 1.10.1 with the fix 121 branch. My rtmp stream has aac audio. the dash *.m4a files being generated cannot be played using vlc if I manually download one.. (VLC can't recognize the input's format). when I go to http://dashif.org/reference/players/javascript/1.4.0/samples/dash-if-reference-player/ it shows the video fine but confirms no audio stream available. here's a snip of my conf file.
location /dash{
                types {
                   application/dash+xml mpd;
                   video/mp4 m4v;
                   audio/mp4 m4a;
                }
                alias /www/dash/live;
                add_header "Cache-Control" "no-cache";
                add_header "Access-Control-Allow-Origin" "*";
                if_modified_since off;
                add_header Last-Modified "";
               #etag off;

...
application live {
                live on;
                record off;
                hls on;
                hls_path /www/hls/live;
                hls_fragment 2s;
                dash on;
                dash_fragment 2s;
                dash_playlist_length 60s;
                dash_path /www/dash/live;
                #dash_cleanup off;
                #dash_nested on;
                #wait_key on;

Thanks.. tried a few different streams ffmpeg etc all with the same result.

**Comment by Ethorsen** [comment]
Hey TheStripe,

Did you find out why there is no audio using DASH?  I have the same issue.  You can see the m4a files being generated, but there is no trace of the audio AdaptationSet block in the MPD file.

I'm pushing data in with avconv using h264 and mp3.

Thx
