### ISSUE TITLE
nginx resets rtmp-module?

### ISSUE THREAD

**Issue by iCrawl** [sergey-dryabzhinsky/nginx-rtmp-module#187]
I'm running Ubuntu 16.04 on my VPS and every 12 to 24h nginx seems to reset the rtmp-module and throws me this error.

When I go back into my `/usr/src/nginx` directory where I built nginx with the rtmp-module and install it again it works again.

I'm pretty much out of ideas, the only other issues with people I have found are when they put their rtmp block into the http block but that isn't the issue in that case. Considering I can stream to the rtmp server fine when I reinstall nginx with the rtmp-module.

I mean I could just let a cronjob run every 6h-12h to reinstall the package lol but... eh

```
nginx: [emerg] unknown directive "rtmp" in /etc/nginx/nginx.conf:87
nginx: configuration file /etc/nginx/nginx.conf test failed
```

```
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 2048;
    # multi_accept on;
}

http {
    // basically just the standard nginx 1.10.0 configuration
}

rtmp {
        server {
                listen 1935;
                chunk_size 4096;

                application live {
                        live on;
                        record off;
                        allow publish // my IP;
                        deny publish all;
                }
        }
}
```

If you wanna know how I built it, because I did it differently than the readme.md suggests.

```
apt-get install build-essential devscripts ffmpeg
apt-get build-dep nginx
apt-get source nginx
wget https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/archive/v1.1.7.10.tar.gz
tar xvzf v1.1.7.10.tar.gz
mkdir nginx-1.10.0/debian/modules/nginx-rtmp-module
cp -r nginx-rtmp-module-1.1.7.10/*  nginx-1.10.0/debian/modules/nginx-rtmp-module
```

after that I added `  --add-module=$(MODULESDIR)/nginx-rtmp-module` as the last entry to the `full_configure_flags`

```
debuild -uc -us
dpkg -i nginx-full_*.deb nginx-common_*.deb 
```

**Comment by sergey-dryabzhinsky** [comment]
Check if Ubuntu 16.04 have newer version of nginx: http://packages.ubuntu.com/xenial-updates/nginx
You should probably build module with 1.10.1 nginx version to prevent auto-update.
Or create PPA on launchpad for yourself.

**Comment by krombel** [comment]
As @sergey-dryabzhinsky mentioned, it may be a problem with auto-update.
You may forbid apt to update nginx so your compiled binary won't get overwritten with the one from public repo which has not included the nginx-rtmp-module.

The Command for this may be this (I don't have Ubuntu 16.04 but it should work)
`sudo apt-mark hold nginx`

**Comment by iCrawl** [comment]
I did both of the things mentioned, first of all compiled with 1.10.1 for safety like @sergey-dryabzhinsky  and put the package on hold too.
Aaaand it seemed to work. Thanks for the quick answers. I should have thought about that myself really.
Sorry ;_;
