### ISSUE TITLE
on_play/publish HTTPS support

### ISSUE THREAD

**Issue by MacKirby** [sergey-dryabzhinsky/nginx-rtmp-module#188]
I've read 3/4 issues over on Arut's original repo now relating to HTTPS support with the above listed directives, and how it's non-existent.  Are there any plans to add this feature to this branch?  If not, what's the easiest method to get around this issue without straight up disabling HTTPS on our authentication server?

**Comment by misiek08** [comment]
Just setup local proxy and talk HTTP with localhost and HTTPS from this
proxy to your auth server. Remember to look if proxy is not changing any
header you need to keep unmodified.

27.09.2016 02:39 "MacKirby" <notifications@github.com> napisał(a):

**Comment by MacKirby** [comment]
We didn't quite use this method, instead we used the map function, works like a charm.  Thanks for the push in the right direction though - we may switch to that method in future.
