### ISSUE TITLE
Is a conditional push possible?

### ISSUE THREAD

**Issue by scalhoun** [sergey-dryabzhinsky/nginx-rtmp-module#204]
Something like: `if $name == 'stream_name' push rtmp....`

I'm trying to schedule streams that will also publish to outside sources like Facebook.  I wanted to avoid custom applications for each one as the file could get massive but any input would be great.

If I did use custom applications is their a max file size I should avoid?

**Comment by chriswiggins** [comment]
Use the on_publish notify hooks to set this up. Make a web app that responds to nginx telling it what to do when someone publishes a stream. Works well for us! Take a look in the wiki under directives for more info

On 8/12/2016, at 6:02 AM, Shane Calhoun <notifications@github.com<mailto:notifications@github.com>> wrote:


Something like: if $name == 'stream_name' push rtmp....

I'm trying to schedule streams that will also publish to outside sources like Facebook. I wanted to avoid custom applications for each one as the file could get massive but any input would be great.

If I did use custom applications is their a max file size I should avoid?

-

**Comment by scalhoun** [comment]
@chriswiggins do you have any samples I could see to shed some light on how to do this?  I already use the on_publish webhook to verify the stream is scheduled in our database.  I initially tried to update the nginx config during on_publish and perform a reload via nginx but that doesn't seem to work and never felt like the best way to do it.

**Comment by chriswiggins** [comment]
Yeah sure - we use nodejs with the hapi HTTP framework, so an example might look like this:


```javascript
server.route({
	path: '/notify-publish',
	method: 'POST',
	config: {
		handler: (request, reply) => {
			let streamName = request.payload.name; //name of the published stream

			if(!streamScheduledInDatabase) return reply('Not Scheduled').code(403);

			if(streamName === 'mystream' && databaseSaysGoToFacebook) return reply.redirect('rtmp://facebook.com/publish/my/app');
			if(streamName === 'otherstream' && databaseSaysGoToYoutube) return reply.redirect('rtmp://youtube.com/publish/my/app');

			//No matches, deny
			return reply('Not found').code(404);
		}
	}
});
```


Sending an HTTP 302 code back to nginx on the on_publish event will cause it to push the stream out to the URL that is returned. Does that make sense?

**Comment by scalhoun** [comment]
@chriswiggins Yep, I had no idea you could do that.   Thanks for the sample.

**Comment by chriswiggins** [comment]
No worries. Another thing to note is you need to use IP addresses, not domain names in the returned string otherwise it won't work. I'll update the example later so others don't copy what I've said word for word and not have it work :-)

**Comment by scalhoun** [comment]
@chriswiggins Just wanted to say thanks again, this worked perfect.

**Comment by chriswiggins** [comment]
More than welcome. Open source FTW!
