### ISSUE TITLE
What nginx and rtmp module versions (branch) do you use for HLS live streaming

### ISSUE THREAD

**Issue by selimatmaca** [sergey-dryabzhinsky/nginx-rtmp-module#205]
Hi everyone,
I am trying to do live streaming using HLS and randomly my fragments and index file disappear (deletes itself) and stream ends. My setup is: IPCamera - OBS - Nginx (ffmpeg) - VideoJS. Stream sometimes end in 5 minutes and sometimes in 1 hour. 
First I had this problem with Nginx1.11.6 and arut's master. 
Then I tried Nginx1.11.6 and sergey-dryabzhinsky's latest -dev, and experienced the same problem.
Then I tried 1.9.10 with sergey's a couple of branches. I couldn't get rid of the problem. HLS index and fragments are deleted automatically. I tried many different ffmpeg commands that I could find on the internet.

My question is: I am sure there are some of you who can succesfully do live streaming by using HLS. Can you please tell me what version nginx and what version of rtmp module you are using. So I can try with them.

**Comment by chriswiggins** [comment]
Can you post your nginx config, and your OBS config? It sounds like a key frame interval issue but I can only spot that when we see the configs! :-)

On 10/12/2016, at 5:16 PM, selimatmaca <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi everyone,
I am trying to do live streaming using HLS and randomly my fragments and index file disappear (deletes itself) and stream ends. My setup is: IPCamera - OBS - Nginx (ffmpeg) - VideoJS. Stream sometimes end in 5 minutes and sometimes in 1 hour.
First I had this problem with Nginx1.11.6 and arut's master.
Then I tried Nginx1.11.6 and sergey-dryabzhinsky's latest -dev, and experienced the same problem.
Then I tried 1.9.10 with sergey's a couple of branches. I couldn't get rid of the problem. HLS index and fragments are deleted automatically. I tried many different ffmpeg commands that I could find on the internet.

My question is: I am sure there are some of you who can succesfully do live streaming by using HLS. Can you please tell me what version nginx and what version of rtmp module you are using. So I can try with them.

-

**Comment by selimatmaca** [comment]
Hi Chris, Here is my nginx.conf. 

user  nginxuser;
worker_processes  1;
#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
#pid        logs/nginx.pid;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  10.20.5.238;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

            location /hls {
            # Serve HLS fragments
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;                
            }
            root /tmp/;
            add_header Cache-Control no-cache;
            add_header 'Access-Control-Allow-Origin' '*';
              }





        location / {
           
            root   html;
            index  index.html index.htm;
            add_header 'Access-Control-Allow-Origin' '*';    

        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    

    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}
}


rtmp {
    server {
        listen 1935;

        application live {
            live on;
exec ffmpeg -i rtmp://10.20.5.238/$app/$name -vcodec libx264 -vprofile
baseline -acodec aac -strict -2 -f flv rtmp://10.20.5.238/hls/$name;

}

application hls {
            live on;
            hls on; 
            
            hls_path /tmp/hls/;
           
           }    

    }
}




And My OBS Settings:
[http://www.selimatmaca.com/images/OBS/obs5.png](url)
[http://www.selimatmaca.com/images/OBS/obs6.png](url)

**Comment by lpcollier** [comment]
I'm streaming successfully using HLS, I can post the details later when I'm back at my laptop. In the meantime, I wonder whether it's worth trying streaming from a location other than /tmp - it just doesn't seem quite right to me! Maybe I'm wrong, but I wonder whether some systems aggressively delete files from /tmp? I think it's also a ram disk on some systems. I use /var/whatever 

Lee

Typed with my fingers

**Comment by selimatmaca** [comment]
Dear Lee,
I am looking forward to hear  the details from you when you  get a chance. I have been trying to solve this hls streaming for the last 3 weeks, days and nights. Please also include the versions you are using and ffmpeg command. Thanks a lot.

**Comment by lpcollier** [comment]
Hi,

I used the Arut Master Branch as that's what was linked in the Howto that I initially used.  I have plans to explore more up to date branches when I've got time!

One bug present (at least in the branch I'm using) using variant quality streams is that the master stream is put in the directory $name but in the automatically created playlist it's referred to as $name_src.  I created symlinks within my directory structure to fix this.  Once I'm on a more up to date branch I'll investigate and submit a fix if it's still an issue.

Here is my nginx.conf:

`worker_processes  1;
error_log  logs/error.log debug;
events {
	worker_connections  1024;
	}

rtmp {
	server {
		listen 1935;
		allow play all;

		application live {
			allow play all;
			live on;
			record off;
			push rtmp://localhost:1935/live-hls;
			exec ffmpeg -i rtmp://localhost/$app/$name
				-c:v libx264 -profile:v baseline -b:v 256K -vf "scale=480:trunc(ow/a/2)*2" -f flv -c:a aac -ac 1 -strict -2 -b:a 32k rtmp://localhost/live-hls/$name_low
				-c:v libx264 -profile:v baseline -b:v 768K -vf "scale=800:trunc(ow/a/2)*2" -f flv -c:a aac -ac 1 -strict -2 -b:a 96k rtmp://localhost/live-hls/$name_mid
				-c:v libx264 -profile:v baseline -b:v 1920K -vf "scale=1280:trunc(ow/a/2)*2" -f flv -c:a aac -ac 1 -strict -2 -b:a 128k rtmp://localhost/live-hls/$name_high;
		}

		#creates our "live" full-resolution HLS videostream from our incoming encoder stream and tells where to put the HLS video manifest and video fragments
		application live-hls {
			allow play all;
			live on;
			record all;
			record_path /var/local/video_recordings;
			record_unique on;
			hls on;
			hls_nested on;
			hls_path /var/local/HLS/live;
			hls_fragment 10s;

			hls_variant _low BANDWIDTH=288000; 
			hls_variant _mid BANDWIDTH=448000;
			hls_variant _high BANDWIDTH=1152000;
			hls_variant _src BANDWIDTH=4096000;			}
		
		#allows you to play your recordings of your live streams using a URL like "rtmp://my-ip:1935/vod/filename.flv"
		application vod {
			play /var/local/video_recordings;
			}
		}
	}


http {
	include       mime.types;
	default_type  application/octet-stream;

	server {
		listen 80;
		server_name 192.168.254.178;
		
		#creates the http-location for our full-resolution (desktop) HLS stream - "http://my-ip/live/my-stream-key/index.m3u8"      
		location /live-hls {
			types {
				application/vnd.apple.mpegurl m3u8;
		}
			alias /var/local/HLS/live;
			add_header Cache-Control no-cache;

			# add CORS headers
			if ($request_method = 'OPTIONS') {
		        add_header 'Access-Control-Allow-Origin' '*';
		        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
		        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
		        add_header 'Access-Control-Max-Age' 1728000;
		        add_header 'Content-Type' 'text/plain charset=UTF-8';
		        add_header 'Content-Length' 0;
		        return 204;
			}
			if ($request_method = 'POST') {
		        add_header 'Access-Control-Allow-Origin' '*';
		        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
		        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
			}
			if ($request_method = 'GET') {
		        add_header 'Access-Control-Allow-Origin' '*';
		        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
		        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
			}
	
		}

		
		#allows us to see how stats on viewers on our Nginx site using a URL like: "http://my-ip/stats"     
		location /stats {
			stub_status;
			}

		#allows us to host some webpages which can show our videos: "http://my-ip/my-page.html"     
		location / {
			root   html;
			index  index.html index.htm;
			}   
		}
	}
`

**Comment by chriswiggins** [comment]
@selimatmaca I think I see your problem. Likely it will relate to your HLS fragment length, and the fact that when you re-encode to HLS you're not specifying what the keyframe interval will be (which should be a factor of the playlist length). I'm also curious as to why you have two applications and effectively are converting twice? You could just use one application if OBS feeds in correctly.

Try this config:
```
rtmp {
 server {
    listen 1935;

    application live {
        live on;
        exec ffmpeg -i rtmp://10.20.5.238/$app/$name -vcodec libx264 -vprofile
baseline -x264opts keyint=40 -acodec aac -strict -2 -f flv rtmp://10.20.5.238/hls/$name;

    }

    application hls {
        live on;
        hls on;
        hls_path /tmp/hls/;
        hls_fragment 6s;
        hls_playlist_length 60s;
   }
 }
}
```

What's happening here is we're telling ffmpeg that we want the keyframe interval to be every 40 frames (which is two seconds based on OBS's output frame rate of 20fps), and then we're telling nginx to split every 3 keyframes (6 seconds). This means that everything fits within the correct second boundaries and should fix your issues. Let me know how you get on.

**Comment by chriswiggins** [comment]
@lpcollier Can you open a new issue for your stuff? Best to try and keep this thread to one issue at a  time :-)

**Comment by lpcollier** [comment]
@chriswiggins not an issue, the OP asked for a working example, which I provided.  The comment regarding the implementation bugs was an aside to help the OP get it working properly.

**Comment by selimatmaca** [comment]
Chriss and IPCollier, 
I will try both examples and inform you the results. I really do appreciate your help.  
You asked why I am converting the stream twice and using two applications. 
Honestly This is my first try on streaming, so I just used the examples that I could find on the internet, mixed them up and I guess I lost the logic on the way and get confused more and more. That's why I am converting the stream on OBS and then on FFMPEG. I will correct that and will not convert anything on OBS. I will use the same fps and resolution as my ip camera on OBS. Then I will let ffmpeg handle the conversion. I hope this sounds ok.

**Comment by selimatmaca** [comment]
Hi Guys,
I tested with both configs with Nginx 1.11.6 and Arut's master.
I tested lpcollier's config first and it worked fine for 5 minutes then stuck. 
Then I tried Chris's recommendation and it worked fine for 15 minutes then stuck.
This is my ip camera settings:
http://selimatmaca.com/images/tempPics/camera.png

This is OBS Settings:
Encoder-x264
Audio-Codec-AAC
Audio-Format-44.1khz
Audio-bitrate-64kbps
Resolution-640x480
FPS (frames per second)-20
Keyframe interval-2 seconds (one keyframe every 2 seconds)
x264 CPU Present-veryfast


And this is the full nginx.conf:
http://selimatmaca.com/images/tempPics/nginxConffile.txt


 I am looking forward any recommendations you may give. Thanks.

**Comment by selimatmaca** [comment]
I solved the problem. This turned out to be OBS related. Windows version of OBS cause the index and ts fragments to be deleted automatically before stream ends. I tried mac version of OBS and I have been streaming hls for the last 3 hours without any problems. I really appreciate Chriss and IPCollier's effort to help me. :)
