### ISSUE TITLE
Duration difference between index.m3u8 and concat mp3 file

### ISSUE THREAD

**Issue by dodolzg** [sergey-dryabzhinsky/nginx-rtmp-module#206]
To reduce the latency of hls, here is my config of nginx:
```
application dev_hls {
    live on;
    hls on;
    hls_base_url http://www.test.com/dev/hls/;
    hls_path /data/cdn/dev/hls;
    hls_nested on;
    hls_fragment 1s;
    hls_max_fragment 1s;
    hls_playlist_length 360000s;
    hls_cleanup off;
    drop_idle_publisher 10s;
}
```

Then I convert all ts files to mp3, here is my shell command:
1. `ls -v *.ts|grep "[0-9]"|xargs cat >tmp.ts`
2. `ffmpeg -i tmp.ts -vn -acodec libmp3lame -write_xing 0 -ar 22050 -ab 24k record.mp3`
3. `ffprobe record.mp3` shows that:
>  Duration: 00:06:09.08, start: 0.000000, bitrate: 24 kb/s
    Stream #0:0: Audio: mp3, 22050 Hz, mono, s16p, 24 kb/s

so the mp3 file duration is **369.08s**, but total duration of index.m3u8 is **352.246s**(sum of all #EXTINF).
There is about 17s difference.

When I config hls_max_fragment to 20s, the durations of mp3 and index.m3u8 are approximately equal.
When the hls_max_fragment is too short, the duration of ts files is error?

**Comment by sergey-dryabzhinsky** [comment]
ts duration depends on keyframe interval / GOP of video stream.
Seems if fragment length is too short m3u playlist generates dirty.
