### ISSUE TITLE
DRM / Common Encryption feature

### ISSUE THREAD

**Issue by ut0mt8** [sergey-dryabzhinsky/nginx-rtmp-module#208]
Another one.

We need to secure our live stream with DRM (argh :() . Do you think it was something doable to add common encryption to this module ?

**Comment by matiaspl** [comment]
Search arut's original ngimx-rtmp wiki and mailing lists for the solution
and optimisation of the encryption process. Standard AES HLS encryption
worked out of the box with that one.

Matt

12 gru 2016 13:25 "Raphael Mazelier" <notifications@github.com> napisał(a):

**Comment by ut0mt8** [comment]
Well this is not what I want, I had to be more precise.
My current plan is to implement widevine DRM which it a kind of standard from google.
Widevine use Common Encryption (CENC). 
In fact I have no choice of using any kind of DRM (widevine, playready, or fairply) to please the majors...

**Comment by matiaspl** [comment]
If that's the case, your out of luck for live streams for now. For VOD
there is https://github.com/kaltura/nginx-vod-module.

Matt

2016-12-12 21:20 GMT+01:00 Raphael Mazelier <notifications@github.com>:

**Comment by ut0mt8** [comment]
Well finally I will try to implement it directly in this module.
Lot of work but seems funny.

**Comment by lelikg** [comment]
@ut0mt8 any luck implementing DRM for live streams?

**Comment by ut0mt8** [comment]
I have currently no working code, but I have made some progress.
First I get the full specification of common-encryption, read it and mostly understand it.
I have also a working implementation of aes-ctr in one of my branch which can encrypt a whole sample.  
Rest to write a lot of mp4 atoms/box, and to do understand how make sub-sample encryption.
Or try to release something which is not really conform to the norm but should work.

For now I am fighting with timestamp in the module (and my RTMP encoder which send garbage).

**Comment by ut0mt8** [comment]
It's work ! you can check it in my fork at https://github.com/ut0mt8/nginx-rtmp-module/tree/cenc.
