### ISSUE TITLE
OpenSSL1.1?

### ISSUE THREAD

**Issue by DeadSix27** [sergey-dryabzhinsky/nginx-rtmp-module#211]
Soo has anyone patched that yet and is willing to PR it?

**Comment by AndreasWurm** [comment]
merge https://github.com/arut/nginx-rtmp-module/commit/04f0ab97ac61d181dbfdaa5299412fc3064e95a3 ?

**Comment by mbeacom** [comment]
@DeadSix27 This is resolved in `dev` via: https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/pull/233

**Comment by DeadSix27** [comment]
@mbeacom thx for the quote
