### ISSUE TITLE
HLS glitch every 10s

### ISSUE THREAD

**Issue by TheStripe** [sergey-dryabzhinsky/nginx-rtmp-module#220]
Hi. On nginx 1.11.10 / dev branch I am getting a HLS glitch every 10 seconds. Sometimes the audio drops off completely. (iphone 6). I am using the bitmovin js player. Dash is working fine on desktop and elsewhere. Any ideas?

I did get it close when using ffmpeg with the -sc_threshold 0 flag. But my hdmi rtmp streamer doesn't have that option. 

#I've been playing with the parameters to no avail.  (srv/HLS is a ram drive)
 hls on;
                hls_path /srv/HLS;
                hls_fragment 3s;
                hls_playlist_length 10s;
                hls_sync 2ms;
                hls_fragment_naming system;

                #hls_continuous on;
                hls_cleanup on;
                hls_fragment_naming system;
                hls_datetime system;

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:1067
#EXT-X-TARGETDURATION:10
#EXT-X-DISCONTINUITY
#EXTINF:9.983,
test-77457510.ts
#EXT-X-DISCONTINUITY
#EXTINF:9.983,
test-78357960.ts
#EXT-X-DISCONTINUITY
#EXTINF:10.000,
test-79258050.ts
#EXT-X-DISCONTINUITY
#EXTINF:9.991,
test-80158770.ts
#EXT-X-DISCONTINUITY
#EXTINF:9.986,
test-81059220.ts
#EXT-X-DISCONTINUITY
#EXTINF:9.984,
test-81959670.ts

**Comment by matiaspl** [comment]
It looks to me your stream is screwed up (wrong GOP size). Your segments
are almost 10 seconds long when they should be 3 seconds. Post your ffmpeg
line.

matt

2017-02-17 3:07 GMT+01:00 TheStripe <notifications@github.com>:

**Comment by TheStripe** [comment]
@matiaspl 
here's the ffmpeg command from windows. this exact thing is also happening from my standalone hdmi to rtmp capture device. The arut master plays this without issue (hls) strange!

 ffmpeg.exe -re -i c:/temp/mike.avi -maxrate 1500k -framerate 1 -bufsize 3000k -acodec aac -vcodec libx264 -f flv rtmp://10.1.1.7:5696/live/stream

**Comment by TheStripe** [comment]
I went with the dash reference player instead of bitmovin. Problem solved.
