### ISSUE TITLE
nginx-1.12.0+

### ISSUE THREAD

**Issue by denji** [sergey-dryabzhinsky/nginx-rtmp-module#234]
* https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/archive/v1.1.7.10.tar.gz
* https://nginx.org/download/nginx-1.12.0.tar.gz

```
/usr/local/share/rtmp-nginx-module/ngx_rtmp_core_module.c:568:30: error: passing 'ngx_sockaddr_t' to parameter of incompatible type 'const void *'
    ngx_memcpy(ls->sockaddr, u.sockaddr, u.socklen);
                             ^~~~~~~~~~
src/core/ngx_string.h:102:54: note: expanded from macro 'ngx_memcpy'
#define ngx_memcpy(dst, src, n)   (void) memcpy(dst, src, n)
```

**Comment by sergey-dryabzhinsky** [comment]
Did you tried `dev` branch?
Fix not in master currently.

**Comment by denji** [comment]
https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/commit/6d9a85e061122b1f0e6bf4b69b0471129c967ca4

**Comment by AppHock** [comment]
/Users/Hock/Library/Caches/Homebrew/nginx

**Comment by AppHock** [comment]
Who can tell me, how to solve.

**Comment by AppHock** [comment]
Ronger-peng:~ Hock$ brew install nginx-full --with-rtmp-module
==> Installing nginx-full from homebrew/nginx
==> Downloading https://nginx.org/download/nginx-1.12.0.tar.gz
Already downloaded: /Users/Hock/Library/Caches/Homebrew/nginx-full-1.12.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/nginx-full/1.12.0 --with-http_ssl_mod
==> make install
Last 15 lines from /Users/Hock/Library/Logs/Homebrew/nginx-full/02.make:
#define ngx_memcmp(s1, s2, n)  memcmp((const char *) s1, (const char *) s2, n)
                                                                        ^~
/usr/local/share/rtmp-nginx-module/ngx_rtmp_core_module.c:568:30: error: passing 'ngx_sockaddr_t' to parameter of incompatible type 'const void *'
    ngx_memcpy(ls->sockaddr, u.sockaddr, u.socklen);
                             ^~~~~~~~~~
src/core/ngx_string.h:102:54: note: expanded from macro 'ngx_memcpy'
#define ngx_memcpy(dst, src, n)   (void) memcpy(dst, src, n)
                                                     ^~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/secure/_string.h:65:33: note: expanded from macro 'memcpy'
  __builtin___memcpy_chk (dest, src, len, __darwin_obsz0 (dest))
                                ^~~
2 errors generated.
make[1]: *** [objs/addon/rtmp-nginx-module/ngx_rtmp_core_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
building nginx-full with healthcheck module giving error https://github.com/Homebrew/homebrew-nginx/issues/263

Error: Your Xcode (8.2.1) is outdated.
Please update to Xcode 8.3 (or delete it).
Xcode can be updated from the App Store.

**Comment by chriswiggins** [comment]
Have you cloned the dev branch?

**Comment by denji** [comment]
https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/compare/v1.1.7.10...542106e.diff

**Comment by SwordZJ** [comment]
@AppHock Did you solve this problem yet？ I got the same problem these days too.

**Comment by amannayak0007** [comment]
@AppHock I am having this problem too.
Do you have a solution?

**Comment by Fenrirthviti** [comment]
Use the dev branch, it compiles fine there against 1.12.0

**Comment by amannayak0007** [comment]
@Fenrirthviti Thanks for your quick response. Can you please tell me how can I install the dev branch? Thanks

**Comment by denji** [comment]
wget 'https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/archive/v1.1.7.10.tar.gz'
cd nginx-rtmp-module-1.1.7.10
curl -sL 'https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/compare/v1.1.7.10...542106e.diff' | patch -p1

**Comment by amannayak0007** [comment]
@denji, I am using these commands to install nginx with rtmp module. But unable to install it.
Please help me!! Thanks

brew tap homebrew/nginx
brew options nginx-full
brew info nginx-full
brew install nginx-full --with-rtmp-module --with-debug

Output -->

### amruns-MacBook-Pro:~ amrun$ brew install nginx-full --with-rtmp-module --with-debug
==> Installing nginx-full from homebrew/nginx
==> Downloading https://nginx.org/download/nginx-1.12.0.tar.gz
Already downloaded: /Users/amrun/Library/Caches/Homebrew/nginx-full-1.12.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/nginx-full/1.12.0 --with-http_ssl_module --with
==> make install
Last 15 lines from /Users/amrun/Library/Logs/Homebrew/nginx-full/02.make:
#define ngx_memcmp(s1, s2, n)  memcmp((const char *) s1, (const char *) s2, n)
                                                                        ^~
/usr/local/share/rtmp-nginx-module/ngx_rtmp_core_module.c:568:30: error: passing 'ngx_sockaddr_t' to parameter of incompatible type 'const void *'
    ngx_memcpy(ls->sockaddr, u.sockaddr, u.socklen);
                             ^~~~~~~~~~
src/core/ngx_string.h:102:54: note: expanded from macro 'ngx_memcpy'
#define ngx_memcpy(dst, src, n)   (void) memcpy(dst, src, n)
                                                     ^~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/secure/_string.h:65:33: note: expanded from macro 'memcpy'
  __builtin___memcpy_chk (dest, src, len, __darwin_obsz0 (dest))
                                ^~~
2 errors generated.
make[1]: *** [objs/addon/rtmp-nginx-module/ngx_rtmp_core_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
building nginx-full with healthcheck module giving error https://github.com/Homebrew/homebrew-nginx/issues/263

Error: Your Xcode (8.3) is outdated.
Please update to Xcode 8.3.1 (or delete it).
Xcode can be updated from the App Store.

**Comment by denji** [comment]
@amannayak0007 ready to merge pull-req. Homebrew/homebrew-nginx#281

**Comment by amannayak0007** [comment]
@denji , It's working now. You saved my life bro. Thank you very much.

**Comment by AppHock** [comment]
Thank you very much.




------------------ 原始邮件 ------------------
发件人: "Denis Denisov";<notifications@github.com>;
发送时间: 2017年4月20日(星期四) 凌晨0:33
收件人: "sergey-dryabzhinsky/nginx-rtmp-module"<nginx-rtmp-module@noreply.github.com>; 
抄送: "轩丶danger"<394496024@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [sergey-dryabzhinsky/nginx-rtmp-module] nginx-1.12.0+ (#234)




wget 'https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/archive/v1.1.7.10.tar.gz'
 cd nginx-rtmp-module-1.1.7.10
 curl -sL 'https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/compare/v1.1.7.10...542106e.diff' | patch -p1
