### ISSUE TITLE
Logging RTMP publishing

### ISSUE THREAD

**Issue by timrettop** [sergey-dryabzhinsky/nginx-rtmp-module#262]
Hello, I'm curious, currently the RTMP module logs "PUBLISH" when my RTMP encoder closes its rtmp session, however there is nothing logged when it starts. 

Is there any way to log when RTMP connections start?

**Comment by winkmichael** [comment]
The idea here is that it is logging the data used for the session. If you want to log the publish event itself you will need to make a custom hook using the on_publish event.

**Comment by timrettop** [comment]
Thanks I'll play with that, I missed that option.
