### ISSUE TITLE
Implement EXT-X-PROGRAM-DATE-TIME

### ISSUE THREAD

**Issue by ctaity** [sergey-dryabzhinsky/nginx-rtmp-module#264]
Can implement this TAG of m3u8 EXT-X-PROGRAM-DATE-TIME ?
Is useful for ads, and live thumbanails.
Thanks.

**Comment by paramaggarwal** [comment]
Yes please - I would like to use it to synchronise clients.

**Comment by ctaity** [comment]
related isuue : #125 https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/issues/125

but in the code in file hls/ngx_rtmp_hls_module.c, the tag exists. 

Why dont work? Thanks

**Comment by baxerus** [comment]
`hls_datetime system;` is implemented and does work.

**Comment by ctaity** [comment]
Yes, works, thanks
