### ISSUE TITLE
About this fork

### ISSUE THREAD

**Issue by silverkorn** [sergey-dryabzhinsky/nginx-rtmp-module#27]
Thus maybe unofficial, should we consider this fork as the new actively maintained development of https://github.com/arut/nginx-rtmp-module?

If so, I would give it a :star: :)

I came here to find a MP3 support for HLS, do you judge it relatively stable?

Thanks!

**Comment by SEAPUNK** [comment]
Well, I consider it to be an actively maintained fork.

**Comment by sergey-dryabzhinsky** [comment]
Thank you that you believe in me!
Roman (arut) seems like to do hard work on this module for Nginx inc.
And unfortunately not have much time to maintain project on github.

About MP3 for HLS:
I not tested this so far. So I can't tell it's stable.

About this fork:
I just pull some usable (I think) things from original repo.
And make some new by myself. Just like this project and its goals.
If you don't mind I continue to sync new things with original repo.
And of couse will continue to fix, create etc. as soon as possible.

**Comment by silverkorn** [comment]
Great!
Here's your star! XD

And thanks for the fast follow-up!
