### ISSUE TITLE
Sending the "stop" command stops the current recording, but then starts another.

### ISSUE THREAD

**Issue by godofgrunts** [sergey-dryabzhinsky/nginx-rtmp-module#292]
I'm following the example on [the wiki](https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/wiki/Control-module). When I issue `start` with `curl "http://192.168.1.18/control/record/start?app=live&name=0&rec=all"` the recording start as they should, but when I issue `stop` with `curl "http://192.168.1.18/control/record/stop?app=live&name=0&rec=all"` the recording stops and then immediately makes a new recording.

I'm not sure if this is a bug or something is wrong with my config.

[Here's a video](https://streamable.com/20eji) showing the problem.

And here's my [nginx config](https://hastebin.com/epifitotik.nginx).

**Comment by misiek08** [comment]
You have record *all* and you probably want *manual*. Try it, please.

śr., 17.04.2019, 01:41 użytkownik godofgrunts <notifications@github.com>
napisał:

**Comment by godofgrunts** [comment]
Yep, that was the issue. Thank you!
