### ISSUE TITLE
FFMPEG stuck on "Sending play command for x" for more than 10s

### ISSUE THREAD

**Issue by mkrn** [sergey-dryabzhinsky/nginx-rtmp-module#299]
ffmpeg version 4.1.3-0york1~16.04
nginx version: nginx/1.15.1
environment: Ubuntu 16,  AWS EC2 t3.small instance 

nginx.conf 
```
worker_processes 1;

error_log  logs/error.log info;

events {
    worker_connections  1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application live {
            live on;
            play_restart on;
            drop_idle_publisher 5s;
            wait_video on;
            wait_key on;

            on_publish http://localhost/on_start;
            on_publish_done http://localhost/on_end;

            exec /home/ubuntu/convert.sh $name >> /home/ubuntu/ffmpeg.log 2>&1;
        }
    }
}

```

FFMPEG command
```
ffmpeg -re -i rtmp://localhost/live/$1 \
    -loglevel debug\
    -c:v libx264 \
    -g 60 \
    -x264opts no-scenecut \
    -preset ultrafast \
    -c:a aac \
    -b:a 44100 \
    -r 30 \
    -rtmp_buffer 0 \
    -fflags nobuffer \
    -analyzeduration 0 \
    -strict -2 \
    -flags -global_header \
    -map 0 \
    -bsf:v h264_mp4toannexb \
    -hls_time 2 \
    -hls_list_size 0 \
    -hls_playlist_type event \
    -hls_flags +append_list \
    -b:v 3000k \
    -maxrate 3000k \
    -bufsize 3000k \
    -analyzeduration 1000000 \
    /efs/hls/$1/index.m3u8 |& tee /tmp/ffmpeg.log
```

When the stream starts and FFMPEG starts processing it it is stuck on this step for 10+ seconds before continuing (taken from log):
```
[rtmp @ 0x55d0d8952ec0] Sending play command for 'd0321b3c-6a35-4c0f-b3df-07f27278fba8'
```

**Comment by winkmichael** [comment]
This doesn’t really have anything to do with NGINX-RTMP.

Try the ffmpeg command outside of nginx and I am sure you will find it takes many seconds before it starts. This is likely ffmpeg waiting for a keyframe from the “publisher”. Try reducing the KFI on the publisher. 

Good luck,
Mike

--
Michael McConnell
WINK Streaming;
email: michael@winkstreaming.com
toll-free: 877-GO-4-WINK x 7400
direct: +1 732-705-7442
cell: +506 8706-2389
skype: wink-michael
web: http://winkstreaming.com

**Comment by mkrn** [comment]
@winkmichael  You're right!!! I thought that the setting was in frames, rather than seconds, so I had it at 15!!
Thank you for pointing it out.
