### ISSUE TITLE
Stream live with a delay of 15 minutes

### ISSUE THREAD

**Issue by Tralapo** [sergey-dryabzhinsky/nginx-rtmp-module#312]
I'm using nginx-rtmp to stream a few webcams to the internet live. I use ffmpeg to pull the RTSP stream from the camera and stream it on my website with HLS, pretty basic:

```
       application live {
                live on;
                record off;

                hls on;
                hls_path /tmp/hls;
                hls_fragment 5s;
                hls_playlist_length 30s;
                hls_continuous on;
                hls_nested off;
                hls_cleanup on;
                hls_fragment_naming system;
                hls_type live;

                allow publish 127.0.0.1;
                deny publish all;

                exec_static ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://cameraip:cameraport/camerastream -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/live/camera1;
       }
```
```
        location /hls {
                types {
                        application/vnd.apple.mpegurl m3u8;
                }

                root /tmp;
                if_modified_since off;
                add_header Last-Modified "";
                etag off;
                add_header Cache-Control "no-cache";
                add_header Access-Control-Allow-Origin *;
        }
```

But now I have a use case where I want to stream the content of one of the camera's **with a 15 minute delay**.

It's crucial it still feels like a live stream on the website, so it has to start instantly, keep playing for as long as you want and it should be impossible to skip forward or backward. So basically live, but 15 minutes delayed. 

I feel like I have to get the record directive involved, but I have no clue how I can make it work like a continuous stream? Is it even possible to do this with nginx-rtmp?

**Comment by golyalpha** [comment]
I think it should be possible to achieve that 15 minute delay using buffers. Do you know the video bitrate?

**Comment by golyalpha** [comment]
But yes, you could also use the record directive by having ingest, vod, live applications, where ingest has recording on, vod plays back flvs from the directory ingest is recording to, and finally ingest executes a script which launches ffmpeg (with audio and video codecs set to copy) with a 15 minute delay, taking vod/stream.flv as the source, and outputting it to live/stream.
Once ingest stops receiving a stream, it will close the recorded file, and ffmpeg will "stream" the rest of the vod to the live application that your players will be connecting to.

**Comment by golyalpha** [comment]
This is what the configuration using record and ffmpeg could look like
```
rtmp {
  application ingest {
    live on;
    idle_streams off;
    record all;
    record_path /tmp/recordings;
    exec_push /path/to/copy/script.sh rtmp://localhost/vod/$stream.flv rtmp://localhost/live/$stream;
  }
  application vod {
    play /tmp/recordings;
  }
  application live {
    live on;
    idle_streams off;
  }
}
```

With the copy script looking something like this:
```
#!/bin/bash

sleep 15m

ffmpeg -i $1 -c:v copy -c:a copy $2 &
```

Of course in the live application, you could enable additional features like HLS/DASH playback, etc. (Recording there would be kind of redundant seeing as you already have the recording from ingest)

**Comment by Tralapo** [comment]
Thank you for your time! I will try and experiment with it this weekend.

I'm kind of struggling to understand the logic. How does the sleep make the livestream show things that happend 15 minutes ago?

**Comment by golyalpha** [comment]
It delays the startup of the FFMPEG stream cloner by 15m, and since the cloner is playing back from the VOD of the stream, rather than the stream itself, instead of starting to clone the stream from the 15m mark, it starts to clone it from the beginning, at "realtime" rate (RTMP doesn't send out faster than the video needs to play back), and since the FLV format doesn't need to be "finalized" in order to play back (is the reason why OBS, for example, recommends you use flv or mkv for recording, in case your computer crashes), the VOD of the stream is available right from the start of the stream.

**Comment by golyalpha** [comment]
The reason you need the ffmpeg part is because you want the 15m delayed stream to still behave like a livestream, so you need to take that VOD, and stream it to a livestream application, that doesn't do the 15m delay - that is why you need the three applications, one to ingest and record the stream, another to serve the recording and the third to ingest and stream the delayed stream.

**Comment by Tralapo** [comment]
Very interesting, thank you. As I said I will try it out live this weekend.
Any idea how to control the amount of saved VOD on the disk?

**Comment by golyalpha** [comment]
There are a lot of controls to determine what gets recorded, but the easiest option would be to have something in crontab to periodically remove old recordings.

**Comment by Tralapo** [comment]
I cannot seem to make this work.
Here's a copy of my current RTMP-setup, which is streaming 3 webcams live to the internet 24/7:

RTMP-setup:
```
server {
        listen 1935;
        chunk_size 4096;

        application live {
                live on;
                record off;

                hls on;
                hls_path /tmp/hls;
                hls_fragment 5s;
                hls_playlist_length 30s;
                hls_continuous on;
                hls_nested off;
                hls_cleanup on;
                hls_fragment_naming system;
                hls_type live;

                allow publish 127.0.0.1;
                deny publish all;

                 exec_static ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://cameraip1:cameraport1/camerastream -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/live/cam1;

                 exec_static ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://cameraip2:cameraport2/camerastream -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/live/cam2;

                 exec_static ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://cameraip3:cameraport3/camerastream -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/live/cam3;
        }
}
```

Webserver setup:

```
location /hls {
                types {
                        application/vnd.apple.mpegurl m3u8;
                }

                root /tmp;
                if_modified_since off;
                add_header Last-Modified "";
                etag off;
                add_header Cache-Control "no-cache";
                add_header Access-Control-Allow-Origin *;
        }
```

Now say I want to add another camera, but this one needs to broadcast with a 15 minute delay.
I copied the bash file you mentioned and added the ingest and vod applications.

When I start Nginx, after 15 minutes the 4th stream appears on https://website.tld/hls/cam4.m3u8, but it's realtime, not 2 minutes behind.

**Comment by golyalpha** [comment]
Is the fourth camera being streamed to the ingest app or the live app?

**Comment by golyalpha** [comment]
Basically, your ingest app should look something like this:
```
application ingest {
  live on;
  record all;
  record_path /tmp/recordings;
  allow publish 127.0.0.1;
  allow play 127.0.0.1;
  deny publish all;
  deny play all;
  exec_static ffmpeg -rtsp_transport tcp -stimeout 60000000  -i rtsp://cameraip4:cameraport4/camerastream -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/ingest/cam4;
  exec_push /opt/delay.sh rtmp://localhost/vod/$stream.flv rtmp://localhost/live/$stream;
}

**Comment by Tralapo** [comment]
Does not seem to work, there are no recordings in /tmp/recordings. The folder also doesn't exist.
When I check the nginx service status I see the exec_static processes is pushing a stream to /ingest/ and I see the bash process and the sleep process. After the sleep time is elapsed the bash and sleep processes disappear from the list and appear again a few seconds later.

But there's no cam4 in live and there are no recordings.

**Comment by golyalpha** [comment]
Do you have ffmpeg installed?

**Comment by Tralapo** [comment]
Yes, the other 3 livestreams work fine.

**Comment by golyalpha** [comment]
Alright, try it with this script:
```
#!/bin/bash

sleep 15m

ffmpeg -i $1 -c:v copy -c:a copy $2 > /var/log/ffmpeg.log 2>&1 &
wait
```

and show me the contents of the /var/log/ffmpeg.log if that fails

**Comment by Tralapo** [comment]
First I tried this, with the bash file an exact copy of your last post and the live application like I showed in a previous post. Only thing I changes was the sleep to 2m, for testing. 15 minutes is a long wait haha.

```
        application ingest {
                live on;
                record all;
                record_path /tmp/record;

                allow publish 127.0.0.1;
                allow play 127.0.0.1;
                deny publish all;
                deny play all;

                exec_static ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://cam4IP:cam4Port/Streaming -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/ingest/cam4;

                exec_push /path/vod.sh rtmp://localhost:1935/vod/$stream.flv rtmp://localhost:1935/live/$stream;
        }

        application vod {
                play /tmp/record;
        }
```

When I restart nginx and check nginx service status, I see this:

```
├─12540 nginx: master process /usr/sbin/nginx -g daemon on; master_process on
├─12541 nginx: worker process
├─12542 nginx: cache manager process
├─12543 ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://Cam4IP:Cam4Port/Streaming -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/ingest/cam4
├─12544 ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://Cam1IP:Cam1Port/Streaming -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/live/cam1
├─12545 ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://Cam2IP:Cam2Port/Streaming -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/live/cam2
├─12546 ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://Cam3IP:Cam3Port/Streaming -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/live/cam3
├─12547 /bin/bash /path/vod.sh rtmp://localhost:1935/vod/.flv rtmp://localhost:1935/live/
└─12548 sleep 2m
```
After 2 minutes the last two lines disappear for a second or two and appear again. There's a .flv in the folder, but no delayed livestream. There's no ffmpeg.log in /var/log created.

As you can see there's no streamname in the bash line, so I hardcoded it for a second try:

```
        application ingest {
                live on;
                record all;
                record_path /tmp/record;

                allow publish 127.0.0.1;
                allow play 127.0.0.1;
                deny publish all;
                deny play all;

                exec_static ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://cam4IP:cam4Port/Streaming -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/ingest/cam4;

                exec_push /path/vod.sh rtmp://localhost:1935/vod/cam4.flv rtmp://localhost:1935/live/cam4;
        }

        application vod {
                play /tmp/record;
        }
```

This results in exactly the same outcome, but now with the streamname in the bash line. But still no livestream and no logfile.

```
├─12540 nginx: master process /usr/sbin/nginx -g daemon on; master_process on
├─12541 nginx: worker process
├─12542 nginx: cache manager process
├─12543 ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://Cam4IP:Cam4Port/Streaming -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/ingest/cam4
├─12544 ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://Cam1IP:Cam1Port/Streaming -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/live/cam1
├─12545 ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://Cam2IP:Cam2Port/Streaming -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/live/cam2
├─12546 ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://Cam3IP:Cam3Port/Streaming -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/live/cam3
├─12547 /bin/bash /path/vod.sh rtmp://localhost:1935/vod/cam4.flv rtmp://localhost:1935/live/cam4
└─12548 sleep 2m
```

Then I tried to hardcode the bash file for cam4 only:

```
#!/bin/bash

sleep 2m

ffmpeg -i rtmp://localhost:1935/vod/cam4.flv -c:v copy -c:a copy rtmp://localhost:1935/live/cam4 > /var/log/ffmpeg.log 2>&1 &
wait
```
```
        application ingest {
                live on;
                record all;
                record_path /tmp/record;

                allow publish 127.0.0.1;
                allow play 127.0.0.1;
                deny publish all;
                deny play all;

                exec_static ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://cam4IP:cam4Port/Streaming -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/ingest/cam4;

                exec_push /path/vod.sh;
        }

        application vod {
                play /tmp/record;
        }
```

But the result is exactly the same. No stream, no log.

**Comment by golyalpha** [comment]
Well, that is weird. Sounds like for some reason ffmpeg is not being executed.

**Comment by Tralapo** [comment]
I tried what would happen with the following setup, without the bash file with the delay:

```
        application ingest {
                live on;
                record all;
                record_path /tmp/record;

                allow publish 127.0.0.1;
                allow play 127.0.0.1;
                deny publish all;
                deny play all;

                exec_static ffmpeg -rtsp_transport tcp -stimeout 60000000 -i rtsp://cam4IP:cam4Port/Streaming -vcodec copy -f flv -r 25 -an rtmp://localhost:1935/ingest/cam4;

                exec_push ffmpeg -i rtmp://localhost:1935/vod/cam4.flv -c:v copy -c:a copy rtmp://localhost:1935/live/cam4;
        }

        application vod {
                play /tmp/record;
        }
```

With this setup I see that copy ffmpeg line for a few seconds in the nginx service status, but it disappears quickly. Shows up a few times, but no longer then a second. It does not produce a livestream.

**Comment by golyalpha** [comment]
That sounds like the livestream is crashing for some reason...

**Comment by golyalpha** [comment]
Is the cam4.flv being generated in the recordings folder?

**Comment by Tralapo** [comment]
Yes, that part is working in all different options.
Can also download the flv and play it on my desktop, it's a genuine video.

**Comment by golyalpha** [comment]
And can you use, for example, VLC to playback the RTMP stream from URL? (replace localhost with the ip/hostname of the RTMP server of course)

**Comment by Tralapo** [comment]
`rtmp://IP:1935/live/cam1` works (as expected)
`rtmp://IP:1935/ingest/cam4 ` works (after I comment out `allow play 127.0.0.1`)
`rtmp://IP:1935/vod/cam4.flv` also works
`rtmp://IP:1935/live/cam4` does not work, because it does not exist.

So the issue really seems to be the last stap, converting the saved recording back into a delayed livestream.

**Comment by golyalpha** [comment]
And if you ssh into the server and try to run the `rtmp://localhost:1935/vod/cam4.flv -c:v copy -c:a copy rtmp://localhost:1935/live/cam4` command manually, what's the output?

**Comment by Tralapo** [comment]
Stupid I didn't try that before. Using the code from the bashfile:

`ffmpeg -i rtmp://localhost:1935/vod/cam4.flv -c:v copy -c:a copy rtmp://localhost:1935/live/cam4`

Indeed it fails:
```
[NULL @ 0x555819762000] Unable to find a suitable output format for 'rtmp://localhost:1935/live/cam4'
rtmp://localhost:1935/live/cam4: Invalid argument
```

So, I don't know why I didn't try this before, but I changed the bashfile to include exactly the same ffmpeg parameters as the other regular livestreams:

```
#!/bin/bash

sleep 2m

/usr/bin/ffmpeg -i $1 -vcodec copy -f flv -r 25 -an $2 &
```

This works and the stream is delayed by two minutes.

Thank you very much for investing so much time in my old issue!
I will check out what it will do with disk usage and reliability.

**Comment by golyalpha** [comment]
Aight, it's fine, just so you know, most of the original line could've been kept, all that was neede was the `-f flv` at the output

**Comment by Tralapo** [comment]
Thanks, you are right.
Now I'm going to find out how to make sure the recorded file doesn't grow bigger and bigger and bigger and bigger and bigger.
Easiest way is restarting Nginx which deletes the file, but then you have to wait 15 minutes to get images again.

Nice project for next weekend ;)

**Comment by golyalpha** [comment]
You could periodically restart the ffmpeg stream. That will just go and overwrite the original FLV, but you'll lose those 15 minutes.
