### ISSUE TITLE
Tag release?

### ISSUE THREAD

**Issue by boris-savic** [sergey-dryabzhinsky/nginx-rtmp-module#313]
Hi Sergey,

thanks for continuing great work on nginx-rtmp. I'd prefer to use your up-to-date project instead of the original repo which was not updated in 4 years, but it would really be a lot easier to lock dependencies if you made a tag / release since last tag was made in 2016. 

Thanks.

**Comment by sergey-dryabzhinsky** [comment]
Anytime soon.

**Comment by arrowd** [comment]
Release or a tag would really help downstream packagers.

**Comment by sergey-dryabzhinsky** [comment]
You got it! v1.2.2-r1
