### ISSUE TITLE
First on_publish consistently skipped over

### ISSUE THREAD

**Issue by NickParks** [sergey-dryabzhinsky/nginx-rtmp-module#316]
I've been suing nginx-rtmp for a little over a month, and have had consistently weird issues with the configuration. Specifically the `on_publish` directive. 

An example of my config is here:
```
rtmp {
    server {
        listen 1935;
        ping 30s;

        application myapp {
            live on;

            hls on;
            hls_path /home/ubuntu/tmp/hls;

            on_publish http://<ip address 1>:3030/checkKey;
            on_publish http://<ip address 2>:3050/live;
            on_publish_done http://<ip address 2>:3050/offline;

            drop_idle_publisher 10s;
        }
    }
}
```

As you can see, my configuration requires two `on_publish` calls to be made. One to verify the stream key, the other to activate our services. `IP Address 2` always received the `on_publish` in this configuration. `IP Address 1` did not. And I don't mean that it failed/sent the wrong data. It actually never sends the POST request.

If I flop the two `on_publish` statements seen above, `IP Address 2` then never receives a request. `IP Address 1` starts to.

I've tested this on two different machines, all using the latest release version, and I can reproduce it every time. Consistently the first `on_publish` directive is always skipped when there is more than 1 in the configuration.

Edit: here's the version of nginx-rtmp-module & ubuntu `Generated by nginx-rtmp-module 1.1.7.11-dev, nginx 1.19.1, pid 15367, built Jul 17 2020 00:10:42 gcc 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)`

**Comment by misiek08** [comment]
IIRC on_* directives can take only single URL and the last provided value is used (so it's possible to overwrite global value with local one). Here only IP2 gets notification, because is the last and deepest one in config. You can write fan-out script which receives notification and sends it to 2+ destinations.

**Comment by NickParks** [comment]
Unfamiliar with how fan-out scripts work, I did however just separate what I needed into the single on_publish call. So that service just calls the others now.

I did see a PR which takes on_publish as an array, but I don't think it's been maintained for a while.

**Comment by misiek08** [comment]
Fan-out is probably exactly the thing you did yourself - a script/service calling multiple others when it receives a request.

**Comment by sergey-dryabzhinsky** [comment]
Yes, only one event handler are active. Last one defined in config.
