### ISSUE TITLE
HTTPS in on_event callbacks is broken

### ISSUE THREAD

**Issue by golyalpha** [sergey-dryabzhinsky/nginx-rtmp-module#318]
I've recently tried using https urls in the on_play and on_publish callbacks inside the rtmp application blocks, and during my image build, it failed during test (just configuration testing, nothing else) with 
```
nginx: [emerg] invalid port in url "https://controlplane.cluster.local/api/ingest_control" in /nginx/conf/nginx.conf:22
```
Where nginx.conf L22 is
```
on_play    https://controlplane.cluster.local/api/ingest_control;
```
It's the first on_event declared in the configuration.

**Comment by git001** [comment]
I have also tried to use https for events which doesn't worked. 
It looks to me that HTTPS is not implemented for notification URLs

**Comment by golyalpha** [comment]
I ended up using a local proxy_pass location to use HTTPS for external connectivity to the "controlplane" host, I would've ended up doing it anyway, as that also lets me implement fallback for when the controlplane is unavailable, in which case the RTMP server acts "dumb" and just lets anyone publish and play anything.

**Comment by MichaelMikeJones** [comment]
@golyalpha Can you provide the configuration?

**Comment by golyalpha** [comment]
@MichaelMikeJones 
If you're looking for the fallback implementation, it's not here, I decided to drop it because it wasn't working the way I needed it to:
```
rtmp {
    server {
        listen 1935;

        application ingest {
            # Enable Livestreaming
            live on;

            # Some basic RTMP config
            wait_key on;
            wait_video on;
            drop_idle_publisher 10s;
            idle_streams off;

            # Record everything - we'll use these recordings later on to make VODs on the TV server, also, custom stream delay
            record all;
            record_path /mnt/archive;
            # record_unique on;

            # Use external service for access control
            on_publish http://localhost/ingest_control;

            deny play all;
        }

        application vod {
            # Enable VOD streaming
            play /mnt/archive;

            on_play    http://localhost/ingest_control;
        }

        application ads {
            # Enable VOD streaming
            play /mnt/ads;

            # Use external service for access control and routing
            on_play http://localhost/ads_control;
        }

        application vods {
            play /mnt/archive;
        }
    }
}

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    server {
        listen 80;

        location /stat {
            rtmp_stat all;
            rtmp_stat_stylesheet stat.xsl;
        }
        location /stat.xsl {
            root /nginx/;
        }

        location /ingest_control {
            proxy_pass http://controlplane;
        }

        location /ads_control {
            proxy_pass http://controlplane;
        }
    }
}
```

**Comment by sergey-dryabzhinsky** [comment]
Yes, callbacks are simple HTTP-requests, no https connection stuff done.

**Comment by sergey-dryabzhinsky** [comment]
Solution: use localhost proxy to other location. As @golyalpha suggested.

**Comment by golyalpha** [comment]
Just to clarify - is it possible to use an internal route for the callback proxy?

I personally went with a standard route, but it would be nice if it was possible to define the routes as internal.

**Comment by sergey-dryabzhinsky** [comment]
What do you mean by `internal`?

**Comment by sergey-dryabzhinsky** [comment]
If you want to disallow anyone to make requests to callback proxy - just add
```
allow 127.0.0.1; // or rtmp worker ip
deny all;
```
