### ISSUE TITLE
hls: not enough buffer for NAL

### ISSUE THREAD

**Issue by lhaus** [sergey-dryabzhinsky/nginx-rtmp-module#323]
I'm streaming with an unusually high bitrate (25000kbps), and I randomly get this error. (`hls: not enough buffer for NAL`)
Happens every 5-10 minutes, and when it does, it stops creating new fragments for about 15 seconds, which causes my player to buffer (playlistlen is set to 10 seconds), after which it resumes as normal. I cannot reproduce the error while streaming with a lower bitrate (15000kbps), and a google search only lead me to the source code and an issue on the arut repo from 2013, with no hints other than patching ffmpeg fixed in, which doesn't seem applicable here as I am not using ffmpeg. And leads would be appreciated!

**Comment by ctaity** [comment]
Try put a higher buffer or use srt to send this high bitrate.

**Comment by lhaus** [comment]
@ctaity which buffer are you talking about specifically? i couldn't find anything related in the directives

**Comment by lhaus** [comment]
It seems like patching the file`/hls/ngx_rtmp_hls_module.c` to `#define NGX_RTMP_HLS_BUFSIZE (1024*1024*16)` seems to have fixed it, but it seems unlikely that patching the source code is the right way to go about this

**Comment by ctaity** [comment]
In ffmpeg when you receive, you can put: 

buflen 5s;
 <https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/blob/dev/doc/directives.md#out_queue>
https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/blob/dev/doc/directives.md#buflen


And 

chunk_size

Maximum chunk size for stream multiplexing. Default is 4096. The bigger this value the lower CPU overhead. This value cannot be less than 128.



My experience with high bitrate (streaming 25 to 50 mbps) srt protocol is much better than rtmp.

**Comment by lhaus** [comment]
@ctaity i am not using ffmpeg though... regarding srt, do you know of any good replacement for this module that supports srt? i would love to use it..

**Comment by ctaity** [comment]
https://github.com/Haivision/srt/blob/master/docs/srt-live-transmit.md <https://github.com/Haivision/srt/blob/master/docs/srt-live-transmit.md>

I use srt like this:


—> ffmpeg (pipe or mpeg udp) —> srt-live-tranmit  —> internet —> srt-live-tranmit (udp) —> ffmpeg rtmp —> hls

If you need help with this setup yo can contact me on: ctaity@gmail.com <mailto:ctaity@gmail.com> via hangouts.
