### ISSUE TITLE
Increase the NGX_RTMP_HLS_BUFSIZE for 8k Cameras

### ISSUE THREAD

**Issue by git001** [sergey-dryabzhinsky/nginx-rtmp-module#332]
I have to modify the NGX_RTMP_HLS_BUFSIZE in https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/blob/dev/hls/ngx_rtmp_hls_module.c#L33 to be able to receive streams from 8k Cameras.

It would be nice when it's be possible to increase the buffer with a setting or ad a `#ifdef HIGH_BUFFER...`  at build time.

**Comment by sergey-dryabzhinsky** [comment]
Pushed to `dev`. Try latest code.

**Comment by git001** [comment]
Cool thanks.
