### ISSUE TITLE
RTSP to RTMP stream

### ISSUE THREAD

**Issue by neetkiss** [sergey-dryabzhinsky/nginx-rtmp-module#340]
How can I broadcast an RTSP broadcast over RTMP without using any attachments (like OBS) via nginx?

**Comment by sergey-dryabzhinsky** [comment]
Nope. It's can be done only via some tool, like `ffmpeg` or `OBS`.

**Comment by neetkiss** [comment]
@sergey-dryabzhinsky Thanks for your reply my friend. However, he was able to multicast over nginx with a small player in the project files. I ran the system with shell programming in a few moments of editing the configuration related to ffmp. It's definitely possible. But I'm not now access project files.
