### ISSUE TITLE
Notify module: pass more client data in notifications

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [sergey-dryabzhinsky/nginx-rtmp-module#36]
Need to pass more client data on events:
- on_connect - need to pass some token or other param to auth.
- on_disconnect - disconnected client addr needed. If possible.
- on_play - need token to auth
- on_publish - need token to auth

This 'token' must be passed through RTMP params. May be like this:
- connect with token param, token saved in client session
- play & publish - use saved token
- update - use saved token. And must disconnect / redirect on 4xx/3xx.

Sould split this in several pull requests.

**Comment by misiek08** [comment]
Maybe we should save in some char[] all args sent with RTMP request? So if users connects to /live/test?data1=asd&data2=qwe we should save everything after *?* (all GET args sent with request)?

I think we can make it configurable or hard-coded, so we set maximum length for data (char array size) and everything after *?* that fits into array is saved and passed with events.

Can be done like that?

**Comment by sergey-dryabzhinsky** [comment]
Full URL probably already stored in ```tc_url``` field of session struct.
Need to check if ```query``` string is present.

**Comment by drzz1** [comment]
Sergey how should I make call on notify module to make custom notify on url, for example if I want call just this url (GET):
http://127.0.0.1/xyz.php?abc=123
Thanks

**Comment by sergey-dryabzhinsky** [comment]
You want to trigger callback from AS3 or FMS?

**Comment by sergey-dryabzhinsky** [comment]
@misiek08 I run some tests about POST data from callbacks:
- run command: ```ffmpeg -s 352x288 -r 30 -f video4linux2 -i /dev/video0 -vcodec libx264 -f flv "rtmp://localhost/rtmp/test?some=arg&test=1 live=1 buffer=0 timeout=5"```
- on_connect sends: ```{"app":"rtmp","flashver":"","swfurl":"","tcurl":"rtmp:\\/\\/localhost\\/rtmp","pageurl":"","addr":"127.0.0.1","epoch":"367166365
7","call":"connect"}```
- on_publish sends: ```{"app":"rtmp","flashver":"","swfurl":"","tcurl":"rtmp:\\/\\/localhost\\/rtmp","pageurl":"","addr":"127.0.0.1","clientid":"8","ca
ll":"publish","name":"test","type":"live","some":"arg","test":"1"}```

So we need to add parsed args to connection callback if it possible.

**Comment by sergey-dryabzhinsky** [comment]
To pass args to connection and play/publish need add them to application and stream-name args:
```ffplay "rtmp://localhost/rtmp?token=12345&uid=431 playpath=test?token=12345&uid=431 live=1 buffer=0 timeout=5"```
In actionscript it must be passed to connection URI and to streamName.

**Comment by drzz1** [comment]
@sergey-dryabzhinsky I want trigger url from rtmp module, not from actionscript or fms

Thanks

**Comment by sergey-dryabzhinsky** [comment]
@drzz1 Standard notify callbacks is not enough for you? https://github.com/arut/nginx-rtmp-module/wiki/Directives#notify
What are you trying to achieve?

**Comment by sergey-dryabzhinsky** [comment]
As described in https://github.com/arut/nginx-rtmp-module/wiki/Directives#notify and checked in previous comments - this issue is not a issue at all.
I closing it.

@drzz1 if your question is complicated - feel free to open new issue.
