### ISSUE TITLE
rtmp connection args is not passed to hls

### ISSUE THREAD

**Issue by drzz1** [sergey-dryabzhinsky/nginx-rtmp-module#37]
ngx_rtmp_hls_publish(ngx_rtmp_session_t *s, ngx_rtmp_publish_t *v)
in this function v.args always are empty, even they are passed when connected to server.
trying access s.args makes crash.

How can get args, swf_url,flashver inside this function?
Thanks

**Comment by sergey-dryabzhinsky** [comment]
You can get them from session ```s```. Thes vars filled at connection time and stored in session var.

**Comment by drzz1** [comment]
I tried already get args from "s" , hls push fails but nginx keeps working if I put this:
ngx_log_error(NGX_LOG_ERR, s->connection->log, 0,"args='%s' ", s->args);
Thanks

**Comment by sergey-dryabzhinsky** [comment]
I think that happens cos this is HTTP module, not RTMP.
How you try to push HLS streams?

**Comment by drzz1** [comment]
rtmp://127.0.0.1/hls?t=152003567
so I want get this "t" parameter, is there other way to pass those parameters to hls module?
Thanks

**Comment by drzz1** [comment]
this solved:
ngx_log_error(NGX_LOG_ERR, s->connection->log, 0,"args='%V' ", &s->args);
