### ISSUE TITLE
calling custom url from rtmp module

### ISSUE THREAD

**Issue by drzz1** [sergey-dryabzhinsky/nginx-rtmp-module#41]
how to make get request on url, for example http://localhost/mynotofication.php
without using built in notification system:
https://github.com/arut/nginx-rtmp-module/wiki/Directives#notify

Thanks

**Comment by sergey-dryabzhinsky** [comment]
How do you imaging that? What you want to do to trigger request?
There is no way to do request on nothing at all. Only if triggered by some event.

**Comment by sergey-dryabzhinsky** [comment]
No answer. I closing issue.
