### ISSUE TITLE
on_*_done bytes values

### ISSUE THREAD

**Issue by misiek08** [sergey-dryabzhinsky/nginx-rtmp-module#47]
Is it easy to add bytes value to those events? I check nginx stat page for that and wasn't editing notify stuff to not break it, but putting send and received bytes count in those events (or only in on_done) will make accounting much easier and accurate.

**Comment by sergey-dryabzhinsky** [comment]
What are you trying to achieve? Why stat page not enough?

**Comment by misiek08** [comment]
I have a case, where I need to know exactly how much bandwidth was used by streams. Since nginx can't add application at runtime I use shared application for all projects and only streams are named $project_streamid.

Stat page is ok, but when user disconnects he disappear from stat oage and I can't get any info about it. So I need bytes sent and received info for every stream, not on application scope.

**Comment by sergey-dryabzhinsky** [comment]
Sounds reasonable. Probably even ```on_disconnect``` should send some stats.

**Comment by misiek08** [comment]
on_disconnect, on_play_done and on_publish_done are the events where it makes sense. on_disconnect is easiest I think.

**Comment by sergey-dryabzhinsky** [comment]
Please check module code from ```on-done-events-send-bytes``` branch.

**Comment by sergey-dryabzhinsky** [comment]
Done in #50 
Merged
