### ISSUE TITLE
errors on installation with wheezy

### ISSUE THREAD

**Issue by maikyyy** [sergey-dryabzhinsky/nginx-rtmp-module#49]
/home/build/nginx-rtmp-module-master/ngx_rtmp_live_module.c: In function ‘ngx_rtmp_live_data’:
/home/build/nginx-rtmp-module-master/ngx_rtmp_live_module.c:1059:37: error: variable ‘msg_type’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/nginx-rtmp-module-master/ngx_rtmp_live_module.o] Fehler 1
make[1]: Leaving directory `/home/build/nginx-1.9.5'
make: *** [build] Fehler 2
root@ns374814:/home/build/nginx-1.9.5# make install
make -f objs/Makefile install
make[1]: Entering directory `/home/build/nginx-1.9.5'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I/home/build/nginx-rtmp-module-master  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/mail -I src/stream \
                -o objs/addon/nginx-rtmp-module-master/ngx_rtmp_live_module.o \
                /home/build/nginx-rtmp-module-master/ngx_rtmp_live_module.c
/home/build/nginx-rtmp-module-master/ngx_rtmp_live_module.c: In function ‘ngx_rtmp_live_data’:
/home/build/nginx-rtmp-module-master/ngx_rtmp_live_module.c:1059:37: error: variable ‘msg_type’ set but not used [-Werror=unused-but-set-variable]
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/nginx-rtmp-module-master/ngx_rtmp_live_module.o] Fehler 1
make[1]: Leaving directory `/home/build/nginx-1.9.5'
make: *** [install] Fehler 2

nginx 1.9.5
module from master

**Comment by sergey-dryabzhinsky** [comment]
Strange, it's used on https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/blob/master/ngx_rtmp_live_module.c#L1079

**Comment by sergey-dryabzhinsky** [comment]
Builded lastest master with 1.9.6 and ```-Wall -Wpointer-arith -Wno-unused-parameter -Werror```.
No errors.

**Comment by maikyyy** [comment]
Problem still exists on debian wheezy and nginx 1.9.6!

/home/build/nginx-rtmp-module-master/ngx_rtmp_live_module.c: In function ‘ngx_rtmp_live_data’:
/home/build/nginx-rtmp-module-master/ngx_rtmp_live_module.c:1059:37: error: variable ‘msg_type’ set but not used [-Werror=unused-but-set-variable]

Please tell us how did you compile with errors.

**Comment by sergey-dryabzhinsky** [comment]
Are you are using stock Debian toolchain?
```
$ gcc -v 2>&1 | grep "gcc version"
gcc version 4.7.2 (Debian 4.7.2-5) 
```

Please tell me more about your build environment.

**Comment by maikyyy** [comment]
yes

root@xxxxxx:~# gcc -v 2>&1 | grep "gcc version"
gcc version 4.7.2 (Debian 4.7.2-5)

**Comment by sergey-dryabzhinsky** [comment]
Try to disable second CFLAGS line in ```nginx-rtmp-module/config``` file and enable first.
Or if it's disabled - try not to use ```-Werror``` gcc flag by default to build nginx:
```
export CFLAGS="-O2 -pipe"
export CXXFLAGS="-O2 -pipe"
export CORE_LINK="-Wl,-O1 -Wl,--as-needed"
./configure .... alot of nginx configure options ....
make
```

**Comment by sergey-dryabzhinsky** [comment]
Or you can try my builds from [gDrive folder](https://drive.google.com/folderview?id=0B6CU04AyADvoU3U2bTd6UVVpV1U&usp=sharing)

**Comment by remiq** [comment]
I've had the same error in Ubuntu after I tried `./configure --add-module=../nginx-rtmp-module --without-http_rewrite_module`. Then I've installed `libpcre3 libpcre3-dev` and it worked fine.

**Comment by farfelu** [comment]
I get the same error on Jessie using v1.1.7.9 and nginx 1.9.7

`gcc version 4.9.2 (Debian 4.9.2-10)`


```
../nginx-rtmp-module/ngx_rtmp_live_module.c: In function 'ngx_rtmp_live_data':
../nginx-rtmp-module/ngx_rtmp_live_module.c:1059:37: error: variable 'msg_type' set but not used [-Werror=unused-but-set-variable]
     u_char                         *msg_type;
                                     ^
```


configuration:
```
./configure --user=nginx \
            --group=nginx \
            --prefix=/usr \
            --conf-path=/etc/nginx/nginx.conf \
            --pid-path=/var/run/nginx.pid \
            --error-log-path=/var/log/nginx/error.log \
            --http-log-path=/var/log/nginx/access.log \
            --with-cc-opt='-O2' \
            --with-file-aio \
            --with-ipv6 \
            --with-http_ssl_module \
            --with-http_v2_module \
            --with-http_realip_module \
            --with-http_addition_module \
            --with-http_xslt_module \
            --with-http_image_filter_module \
            --with-http_geoip_module \
            --with-http_sub_module \
            --with-http_dav_module \
            --with-http_flv_module \
            --with-http_mp4_module \
            --with-http_gunzip_module \
            --with-http_gzip_static_module \
            --with-http_random_index_module \
            --with-http_secure_link_module \
            --with-http_degradation_module \
            --with-http_stub_status_module \
            --with-http_perl_module \
            --with-mail \
            --with-mail_ssl_module \
            --with-google_perftools_module \
            --with-pcre=../pcre-8.37 \
            --with-zlib=../zlib-1.2.8 \
            --add-module=../nginx-rtmp-module
```
`objs/Makefile` contained:
```
CFLAGS =  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O2 -I../nginx-rtmp-module
```
I've already tried without `--with-cc-opt='-O2'`, it didn't make any difference.

**Comment by sergey-dryabzhinsky** [comment]
Try to add ```--with-debug``` configure option.

**Comment by farfelu** [comment]
using `--with-debug` works.

I'm still wondering where `-Werror=unused-but-set-variable` comes from, none of the libraries sets it anywhere.

**Comment by sergey-dryabzhinsky** [comment]
It's from ```-Werror```. If you are building a Debian package it can be pulled on by default build environment.
Check output of ```env DEB_BUILD_MAINT_OPTIONS=hardening=+all dpkg-buildflags --get CFLAGS```.
On Ubuntu 14.04 it produce: ```-g -O2 -fPIE -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security```.

**Comment by sergey-dryabzhinsky** [comment]
If debug not enabled then all log macros are empty and var really not used.

Try latest code from master. I think I fixed this.

**Comment by farfelu** [comment]
using the latest master (4c7dd6ed005e82865364f817c264430f1cc46f86) gets me
```
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -O2 -I../nginx-rtmp-module  -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../pcre-8.37 -I ../zlib-1.2.8 -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/http/modules/perl -I src/mail -I src/stream -o objs/addon/nginx-rtmp-module/ngx_rtmp_stat_module.o ../nginx-rtmp-module/ngx_rtmp_stat_module.c
../nginx-rtmp-module/ngx_rtmp_live_module.c: In function 'ngx_rtmp_live_postconfiguration':
../nginx-rtmp-module/ngx_rtmp_live_module.c:1513:19: error: 'ngx_rtmp_live_on_text_data' undeclared (first use in this function)
     ch->handler = ngx_rtmp_live_on_text_data;
                   ^
../nginx-rtmp-module/ngx_rtmp_live_module.c:1513:19: note: each undeclared identifier is reported only once for each function it appears in
../nginx-rtmp-module/ngx_rtmp_live_module.c:1517:19: error: 'ngx_rtmp_live_on_cue_point' undeclared (first use in this function)
     ch->handler = ngx_rtmp_live_on_cue_point;
                   ^
objs/Makefile:1671: recipe for target 'objs/addon/nginx-rtmp-module/ngx_rtmp_live_module.o' failed
```

with and without `--with-debug`

**Comment by sergey-dryabzhinsky** [comment]
Damn! Forgot to uncomment functions. Fixed in latest master.

**Comment by farfelu** [comment]
compiles with and without `--with-debug` on 06e49e05fdaf3dc1c21d638d6657168572299967
Hooray!

**Comment by sergey-dryabzhinsky** [comment]
@maikyyy, try latest code from master.

**Comment by maikyyy** [comment]
seems to be ok, good work!

**Comment by sergey-dryabzhinsky** [comment]
Good, closing issue.
