### ISSUE TITLE
Please fix build error on windows environment

### ISSUE THREAD

**Issue by kgp700** [sergey-dryabzhinsky/nginx-rtmp-module#60]
Hi
When I was build your source, It occurred error
I was build with Visual Studio 2010 command prompt on Windows 8.1

objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(6) : error C2220: 경고가 오류로 처리
되어 생성된 'object' 파일이 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(6) : warning C4627: '#include <sys/ti
me.h>': 미리 컴파일된 헤더 사용을 찾을 때 건너뛰었습니다.
        'ngx_config.h'에 지시문 추가 또는 미리 컴파일된 헤더 다시 빌드
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(615) : error C2143: 구문 오류 : ';'이
(가) '형식' 앞에 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(626) : error C2143: 구문 오류 : ';'이
(가) '형식' 앞에 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(646) : error C2143: 구문 오류 : ';'이
(가) '형식' 앞에 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(669) : error C2065: 'out_elts' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(669) : error C2109: 첨자는 배열 또는
포인터 형식을 사용해야 합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(670) : error C2065: 'out_inf' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(670) : error C2109: 첨자는 배열 또는
포인터 형식을 사용해야 합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(673) : error C2065: 'out_inf_ex_data'
 : 선언되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(673) : error C2109: 첨자는 배열 또는
포인터 형식을 사용해야 합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(681) : error C2065: 'out_elts' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(681) : warning C4047: '함수' : 'ngx_r
tmp_amf_elt_t *'의 간접 참조 수준이 'int'과(와) 다릅니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(681) : warning C4024: 'ngx_rtmp_creat
e_amf' : 형식 및 실제 매개 변수 3의 형식이 서로 다릅니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(682) : error C2065: 'out_elts' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(682) : error C2065: 'out_elts' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(682) : error C2109: 첨자는 배열 또는
포인터 형식을 사용해야 합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(682) : error C2198: 'ngx_rtmp_create_
amf' : 호출에 매개 변수가 너무 적습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(687) : error C2061: 구문 오류 : 식별
자 'ngx_rtmp_send_redirect_status'
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(687) : error C2059: 구문 오류 : ';'
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(687) : error C2059: 구문 오류 : '형식
'
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(879) : error C2079: 'tz'은(는) 정의되
지 않은 struct 'timezone'을(를) 사용합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(919) : warning C4013: 'gettimeofday'
이(가) 정의되지 않았습니다. extern은 int형을 반환하는 것으로 간주합니다.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0
\VC\BIN\cl.EXE"' : '0x2' 반환 코드입니다.

Sorry for korean language. I'm using korean visual studio
But I think you can understand what is problem
no problem build https://github.com/arut/nginx-rtmp-module source
only your source have build problem

Please fix it.
Thanks

**Comment by sergey-dryabzhinsky** [comment]
Can you pealse try sources from branch ```i60-fix-build-on-windows-timeh-missing```

**Comment by kgp700** [comment]
Thanks for fast support
I tried build  i60-fix-build-on-windows-timeh-missing branch
but It had error too

objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(613) : error C2143: 구문 오류 : ';'이
(가) '형식' 앞에 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(624) : error C2143: 구문 오류 : ';'이
(가) '형식' 앞에 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(644) : error C2143: 구문 오류 : ';'이
(가) '형식' 앞에 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(667) : error C2065: 'out_elts' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(667) : error C2109: 첨자는 배열 또는
포인터 형식을 사용해야 합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(668) : error C2065: 'out_inf' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(668) : error C2109: 첨자는 배열 또는
포인터 형식을 사용해야 합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(671) : error C2065: 'out_inf_ex_data'
 : 선언되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(671) : error C2109: 첨자는 배열 또는
포인터 형식을 사용해야 합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(679) : error C2065: 'out_elts' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(679) : warning C4047: '함수' : 'ngx_r
tmp_amf_elt_t *'의 간접 참조 수준이 'int'과(와) 다릅니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(679) : warning C4024: 'ngx_rtmp_creat
e_amf' : 형식 및 실제 매개 변수 3의 형식이 서로 다릅니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(680) : error C2065: 'out_elts' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(680) : error C2065: 'out_elts' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(680) : error C2109: 첨자는 배열 또는
포인터 형식을 사용해야 합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(680) : error C2198: 'ngx_rtmp_create_
amf' : 호출에 매개 변수가 너무 적습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(685) : error C2061: 구문 오류 : 식별
자 'ngx_rtmp_send_redirect_status'
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(685) : error C2059: 구문 오류 : ';'
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(685) : error C2059: 구문 오류 : '형식
'
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(916) : error C2120: 모든 형식에서 'vo
id'를 사용할 수 없습니다.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0
\VC\BIN\cl.EXE"' : '0x2' 반환 코드입니다.
Stop.

**Comment by sergey-dryabzhinsky** [comment]
I updated branch, not shure why it fails on after log macros. Please try to build again.

**Comment by kgp700** [comment]
I tried update branch... still have error

Build with Visual Studio 2010 command prompt :
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(606) : error C2220: 경고가 오류로 처
리되어 생성된 'object' 파일이 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(606) : warning C4013: 'ngx_log_debug'
이(가) 정의되지 않았습니다. extern은 int형을 반환하는 것으로 간주합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(614) : error C2143: 구문 오류 : ';'이
(가) '형식' 앞에 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(625) : error C2143: 구문 오류 : ';'이
(가) '형식' 앞에 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(645) : error C2143: 구문 오류 : ';'이
(가) '형식' 앞에 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(668) : error C2065: 'out_elts' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(668) : error C2109: 첨자는 배열 또는
포인터 형식을 사용해야 합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(669) : error C2065: 'out_inf' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(669) : error C2109: 첨자는 배열 또는
포인터 형식을 사용해야 합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(672) : error C2065: 'out_inf_ex_data'
 : 선언되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(672) : error C2109: 첨자는 배열 또는
포인터 형식을 사용해야 합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(680) : error C2065: 'out_elts' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(680) : warning C4047: '함수' : 'ngx_r
tmp_amf_elt_t *'의 간접 참조 수준이 'int'과(와) 다릅니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(680) : warning C4024: 'ngx_rtmp_creat
e_amf' : 형식 및 실제 매개 변수 3의 형식이 서로 다릅니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(681) : error C2065: 'out_elts' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(681) : error C2065: 'out_elts' : 선언
되지 않은 식별자입니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(681) : error C2109: 첨자는 배열 또는
포인터 형식을 사용해야 합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(681) : error C2198: 'ngx_rtmp_create_
amf' : 호출에 매개 변수가 너무 적습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(686) : error C2061: 구문 오류 : 식별
자 'ngx_rtmp_send_redirect_status'
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(686) : error C2059: 구문 오류 : ';'
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(686) : error C2059: 구문 오류 : '형식
'
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(917) : error C2120: 모든 형식에서 'vo
id'를 사용할 수 없습니다.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 10.0
\VC\BIN\cl.EXE"' : '0x2' 반환 코드입니다.
Stop.



and I tried build with Visual Studio 2013 command prompt
Decrease errors

objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(606) : error C2220: 경고가 오류로 처
리되어 생성된 'object' 파일이 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(606) : warning C4013: 'ngx_log_debug'
이(가) 정의되지 않았습니다. extern은 int형을 반환하는 것으로 간주합니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_send.c(917) : error C2120: 모든 형식에서 'vo
id'를 사용할 수 없습니다.
NMAKE : fatal error U1077: 'E:\Visual_Studio_2013\VC\BIN\cl.EXE' : '0x2' 반환 코
드입니다.
Stop.

**Comment by sergey-dryabzhinsky** [comment]
One more update in branch.
Or disable warnings as errors: https://msdn.microsoft.com/library/ksk5k0ta.aspx

**Comment by kgp700** [comment]
I tried new updated source with Visual Studio 2013 command prompt

This error occured

objs/lib/nginx-rtmp-module/ngx_rtmp_codec_module.c(457) : error C2220: 경고가 오
류로 처리되어 생성된 'object' 파일이 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_codec_module.c(457) : warning C4244: '=' : '
uint64_t'에서 'ngx_uint_t'(으)로 변환하면서 데이터가 손실될 수 있습니다.
NMAKE : fatal error U1077: 'E:\Visual_Studio_2013\VC\BIN\cl.EXE' : '0x2' 반환 코
드입니다.
Stop.

I added #pragma warning(disable:4244) to ngx_rtmp_codec_module.h
and then another error occured

objs/lib/nginx-rtmp-module/ngx_rtmp_notify_module.c(1371) : error C2220: 경고가
오류로 처리되어 생성된 'object' 파일이 없습니다.
objs/lib/nginx-rtmp-module/ngx_rtmp_notify_module.c(1371) : warning C4013: 'ngx_
log_debug'이(가) 정의되지 않았습니다. extern은 int형을 반환하는 것으로 간주합니
다.
NMAKE : fatal error U1077: 'E:\Visual_Studio_2013\VC\BIN\cl.EXE' : '0x2' 반환 코
드입니다.
Stop.

I added #pragma warning(disable:4013) to ngx_rtmp_notify_module.c

Then build again
Build was almost done but error occured shortly before out nginx.exe file

ngx_rtmp_notify_module.obj : error LNK2019: _ngx_log_debug 외부 기호(참조 위치:
_ngx_rtmp_notify_play_handle 함수)에서 확인하지 못했습니다.
objs/nginx.exe : fatal error LNK1120: 1개의 확인할 수 없는 외부 참조입니다.
NMAKE : fatal error U1077: 'E:\Visual_Studio_2013\VC\BIN\cl.EXE' : '0x2' 반환 코
드입니다.
Stop.

I can't do anything more now...

**Comment by sergey-dryabzhinsky** [comment]
Hmmm... Can you try latest code from branch and add ```---with-debug``` to nginx configure options?

**Comment by kgp700** [comment]
Thanks :)
Added #pragma warning(disable:4244) to ngx_rtmp_codec_module.h and 
added #pragma warning(disable:4013) to ngx_rtmp_notify_module.c

auto configure with --with-debug

No error. sucess build

Thanks :)
