### ISSUE TITLE
Recover stream

### ISSUE THREAD

**Issue by Tralapo** [sergey-dryabzhinsky/nginx-rtmp-module#62]
I don't know if I should ask this here or on a ffmpeg forum or something, but I will give it a try here first.

I stream a few IP-camera's with nginx-rtmp and I use exec_static to pull the rtsp stream from the camera en push it to rtmp://localhost:1935/name with ffmpeg.

Every time when there's a small hickup on the line or the IP-adres of a camera changes and the dyndns needs a minute to update, the stream fails and does not recover.

At the moment I restart Nginx a few times a day, but that's a 'dirty hack' and it's still possible a stream won't be available for a few hours.

Is there a way to make it recover again? I guess exec_pull would fix it, but that's not an option as I am only using HLS ( #59 )

**Comment by sergey-dryabzhinsky** [comment]
You should try to set ```respawn on;``` on ```rtmp { ... }``` section level.

**Comment by sergey-dryabzhinsky** [comment]
Also you can try to emulate ```exec_pull``` for http - hls/dash with Lua/Perl or Echo modules.
Lua and Perl may be too difficult to start with.
As for Echo, main idea is:
1. add to hls/dash location code: ```echo_location_async @execpull app=some-rtmp-app from=camera1-uri stream=result-stream-name;```
2. create new location:
```
location @execpull {
    internal;
    include fastcgi_params;
    fastcgi_pass /path/to/ffmpeg-statup-script.fcgi
}
```
3. write that fcgi script on python/perl/php. It must:
    1. check and start ffmpeg if it not started
    2. update some timestamp of last call requested - simple ```touch /tmp/some-file-name``` or use sqlite3 db or anything.
    3. check every double hls/dash chunk interval if there was new request. And stop ffmpeg if not.
    4. script must not return anything to not destroy original request output.
4. Params app. from, stream - must be in QUERY_STRING env. Script got them, parse, set into ffmpeg call cmd.

**Comment by Tralapo** [comment]
> You should try to set respawn on; on rtmp { ... } section level.

From the Wiki I understood respawn is on by default, so I tought this wasn't needed. I added it now inside the rtmp section, and it seems like it helps a bit. I rebooted one of the camera's to check what would happen. After it came up again, I did not get a 404 on my .m3u8 file, which was the case before. However, I still get 404's on the .ts chunks inside them, so it seems like it's not working as expected.

This is my code right now:

```
rtmp_auto_push on;

rtmp {
	respawn on;
	server {
		listen 1935;
		chunk_size 4096;

		application live {
			live on;
            record off;

            hls on;
            hls_path /tmp/hls;
            hls_fragment 10s;
            hls_playlist_length 30s;
            hls_continuous on;

            allow publish 127.0.0.1;
            deny publish all;

            exec_static ffmpeg -rtsp_transport tcp -i rtsp://ipcamera/stream -re -ar 44100 -ac 2 -acodec pcm_s16le -f s16le -ac 2 -i /dev/zero -f h264 -vcodec copy -acodec aac -ab 128k -g 50 -strict experimental -f flv rtmp://localhost:1935/live/stream;

			}
		}
}
```

**Comment by sergey-dryabzhinsky** [comment]
Try to add to ffmpeg command:
```exec_static ffmpeg -rtsp_transport tcp -stimeout 60000000 ...```
By http://ffmpeg.org/ffmpeg-protocols.html#rtsp
```
stimeout

    Set socket TCP I/O timeout in microseconds.
```

**Comment by sergey-dryabzhinsky** [comment]
Second comment is about how to try to emulate ```exec_pull``` on ```http``` requests to HLS/DASH locations.
It tricky, yes.

**Comment by Tralapo** [comment]
```stimeout``` seems to work! Thank you very much!

**Comment by matiaspl** [comment]
>             exec_static ffmpeg -rtsp_transport tcp -i
rtsp://ipcamera/stream -re -ar 44100 -ac 2 -acodec pcm_s16le -f s16le -ac 2
-i /dev/zero -f h264 -vcodec copy -acodec aac -ab 128k -g 50 -strict
experimental -f flv rtmp://localhost:1935/live/stream;
>

Using -re as an output option doesn't make much sense to me. As an input
option it can fix various problems but from my own experience at the same
time it may lead to ffmpeg deadlocks. I have no idea what it does to the
output.

Matt

**Comment by Tralapo** [comment]
I'm not an expert on ffmpeg. I had to make a stream work for YouTube Live too and this one worked. YouTube is very strict on incoming stream formats.

**Comment by Tralapo** [comment]
@sergey-dryabzhinsky About your suggestions: it sounds interesting to me, but I'm a bit puzzled about the fcgi-script part. Do you maybe have some links to point me in the right direction? I have a location coming up where the IP-camera is connected to a connection with a data-cap, so a solution like that would definitely be a good thing to have for that case.

**Comment by sergey-dryabzhinsky** [comment]
About ```-re``` - it makes no sense to output.
About FastCGI - try to start with some simple scripts, like http://webpy.org/cookbook/fastcgi-nginx  or http://flask.pocoo.org/docs/0.10/deploying/fastcgi/

**Comment by Tralapo** [comment]
By the way, I removed ```-re``` and it had dramatic effects on the streams. Irregular stops, hickups, repeats?

**Comment by matiaspl** [comment]
Curious... makes me question everything I have learned about ffmpeg command
line syntax.
Then maybe it's an input only option, so works regardless which side of the
-i it's being put.
You may have luck with -vsync 0 or -vsync 1 too (use it as an input option,
so before -i), but I know there are cases where -re with occasional
freezes, restarts and gaps work fine ;)

The issue is that with consumer grade electronics you never know if one
second actually takes as lonf as "one second from Sevres". And that's
pretty important because -re assumes that it gets a frame every single
interval determined by the TBR (or FPS - I don't remember which one). If it
doesn't or it gets too many of them bad things like buffer over- or
underruns are bound to happen. Everything works fine for file input,
because all frames are already available, but for streams it's not
recommended.

Matt

2016-01-06 18:14 GMT+01:00 Tralapo <notifications@github.com>:
