### ISSUE TITLE
digest auth without php

### ISSUE THREAD

**Issue by victusfate** [sergey-dryabzhinsky/nginx-rtmp-module#68]
Is there a simple way to use publisher auth w/o php? 

Looking over the docs and [examples](http://www.helping-squad.com/nginx-rtmp-secure-your-nginx-server/) I've seen on_publish forwarded to auth.php

**Comment by misiek08** [comment]
You can use any language or even embed Lua to nginx with Lua-module and you
will have all-in-one solution.

**Comment by victusfate** [comment]
awesome, thanks!

**Comment by mbeacom** [comment]
@misiek08 Are you using the full `openresty` build or just the https://github.com/openresty/lua-nginx-module module?
Thanks!

**Comment by misiek08** [comment]
Personally I use openresty but without nginx-rtmp. I just run 2 separate
nginx instances, one for http stuff(hls, auth, lua generated dynamic pages)
and second with rtmp and rtmp stats.

**Comment by victusfate** [comment]
ok, so the rtmp nginx forwards it's auth checks to the http nginx instance?

**Comment by misiek08** [comment]
Exactly.

**Comment by jstabenow** [comment]
not tested, but the first example can be a solution:
https://github.com/arut/nginx-rtmp-module/issues/347

**Comment by sergey-dryabzhinsky** [comment]
Yes, when you connect to rtmp, like: ```ffplay "rtmp://localhost/live?token=123 playpath=stream live=1"```,  then nginx-rtmp will do subrequest ```on_connect http://localhost/on-connect```.

Which can be proxyed to any backend - php, perl, lua. And ```token``` parameter will ba passed through GET/POST.

And if backend not returned HTTP 200 code - rtmp request will be dropped.

**Comment by sergey-dryabzhinsky** [comment]
Hope answer was useful.
Closing.
