### ISSUE TITLE
$name manipulation

### ISSUE THREAD

**Issue by ryanpager** [sergey-dryabzhinsky/nginx-rtmp-module#72]
So in my directive, I publish a stream with the following syntax,

rtmp://localhost/broadcast/sudovoodoo-<uuid>-1

In my application, I need to chop off the "-1" from the name so that subscribers dont see that increment (which is used for recording). Is there a way to change the $name variable once its been set, or is there away to dynamically alter it?

**Comment by matiaspl** [comment]
Use timestamped record file names. You can have static uplink stream names
then.

Matt

2016-02-18 17:41 GMT+01:00 Ryan Page <notifications@github.com>:

**Comment by sergey-dryabzhinsky** [comment]
There is no way to do that in nginx-rtmp.
What are you trying to achieve by that?

**Comment by ryanpager** [comment]
@sergey-dryabzhinsky Yea -- it was a dumb idea. I figured out a work around. Sorry about that.
