### ISSUE TITLE
rtmp stream doesn't show after some time after broadcast start

### ISSUE THREAD

**Issue by ryr** [sergey-dryabzhinsky/nginx-rtmp-module#73]
Стрим воспроизводится если подключиться в самом начале трансляции, либо до ее начала. В этом случае все нормально работает на всем протяжении трансляции.

Если запустить воспроизведение позже, то нет ни картинки, ни звука.

настройки rtmp.conf:
```
application live {
    live on;
}
```

Для трансляции используется OBS, воспроизведение - Chrome/Firefox и videojs

Пробовал https://github.com/ossrs/go-oryx - таких проблем не наблюдается, потому вряд ли проблема в OBS или браузерах/videojs

**Comment by sergey-dryabzhinsky** [comment]
1. С какими параметрами создается поток в OBS?
2. Проигрывается через videojs какой поток rtmp? hls? dash? Какие настройки передаются скрипту?
3. Пробовали проигрывать через ffmpeg? ```ffplay rtmp://server/app/stream```

**Comment by ryr** [comment]
1. по идее без разницы, т.к. пробовал через ffmpeg транслировать, результат тот же.
2. rtmp. с hls все нормально работает, но нужна минимальная задержка. 
3. пробовал различные варианты, один из них:
```
exec /usr/bin/ffmpeg -loglevel warning -i rtmp://localhost/$app/$name -threads 8 -async 1 -vsync -1
        -c:v libx264
        -c:a aac -strict -2
        -b:v 768k
        -b:a 96k
        -flags +global_header
        -vf scale=-2:360
        -tune zerolatency
        -preset veryfast
        -pix_fmt yuv420p
        -force_key_frames "expr:gte(t,n_forced*2)"
        -crf 23
        -f flv rtmp://localhost/view/$name
```

**Comment by ryr** [comment]
добавил 
```
rtmp_auto_push on;
```
все заработало

**Comment by sergey-dryabzhinsky** [comment]
Такое бывает, если кол-во worker-ов nginx-а указано более 1.
Поставьте ```worker_processes 1;```, т.к. nginx-rtmp не создавался для работы в многопроцессном режиме. Только с хаками в виде auto_push.

**Comment by ryr** [comment]
понял, спасибо!
