### ISSUE TITLE
Build ngx_rtmp_module as a dynamic module

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [sergey-dryabzhinsky/nginx-rtmp-module#78]
And support nginx 1.9.11+

Original request: https://github.com/arut/nginx-rtmp-module/pull/762

**Comment by sergey-dryabzhinsky** [comment]
This config is copied from
https://www.nginx.com/resources/wiki/extending/converting/#complex-example

**Comment by sergey-dryabzhinsky** [comment]
Done in #79

**Comment by nitsuj102284** [comment]
@sergey-dryabzhinsky, I need to add RTMP Module to existing Nginx install. How do I go about doing this. (Nginx was installed by Laravel Forge)
Thank you!
