### ISSUE TITLE
Limits per HLS/DASH location

### ISSUE THREAD

**Issue by jstabenow** [sergey-dryabzhinsky/nginx-rtmp-module#92]
Is there a known way to limit the connections and/or the bandwidth > per < HLS/DASH location?
Would be an great function to provide different configs on one nginx.

Example:
```sh
        location /hls-1 {
            .....

            limit_current_connnections 1000;
            limit_current_bandwidth 10g;

        }
        location /hls-2 {
            .....

            limit_current_connnections 10;
            limit_current_bandwidth 100m;

        }
```

**Comment by sergey-dryabzhinsky** [comment]
You can use standard limit_req and limit_conn modules.
And probably https://github.com/yaoweibin/nginx_limit_speed_module

**Comment by jstabenow** [comment]
Nice tanks! I didn't know this module yet :+1:
