### ISSUE TITLE
FFmpeg stagnates if a stream isn't available

### ISSUE THREAD

**Issue by jstabenow** [sergey-dryabzhinsky/nginx-rtmp-module#94]
I have trouble with FFmpeg if a stream isn't available:
```sh
$ ffmpeg -i rtmp://my-nginx-ip:1935/live/unknown -c copy -f rtmp://my-endpoint
```

A Wowza-Server will return an 404 or something else, so the FFmpeg process dies. But NGINX-RTMP maintains the connection = FFmpeg stagnates and does't close the process.

Is there a known handling? E.g. with "exec_play"?

**Comment by andrew-shulgin** [comment]
https://github.com/arut/nginx-rtmp-module/wiki/Directives#idle_streams

**Comment by jstabenow** [comment]
perfect, thanks!
