### ISSUE TITLE
prevent changing post args

### ISSUE THREAD

**Issue by ryr** [sergey-dryabzhinsky/nginx-rtmp-module#97]
is there a possibility to prevent changing post argumnets (pageurl, addr, clientid etc) passed to on_play?

**Comment by misiek08** [comment]
Client connecting to server can set any value for those variables. There's no way to control it.

**Comment by ryr** [comment]
what about to make this feature? it will be very helpful

**Comment by misiek08** [comment]
It's protocol "feature", nothing to do about this. Any server is vulnerable
if you use those parameters, because user can change then as he like and
any rtmp server will just accept that data.

**Comment by ryr** [comment]
just checked https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/wiki/Directives#rtmp_stat - it returns unmodified (real) querie.
this means it is possible to obtain real data or to prevent changing it.

**Comment by ryr** [comment]
fixed in https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/issues/98
