### ISSUE TITLE
new notify events

### ISSUE THREAD

**Issue by ryr** [sergey-dryabzhinsky/nginx-rtmp-module#98]
it will be great if two new events will be added: on_play_update and on_publish_update

**Comment by chriswiggins** [comment]
Can you elaborate @ryr ? What do you want these to do?

**Comment by ryr** [comment]
atm i cant distinguish between a client or publisher hits on_update notify

**Comment by chriswiggins** [comment]
When you get a request to your on_update notify endpoint, you should get one of the two `call` queries:

`&call=update_publish` or `&call=update_play`

See [ngx_rtmp_notify_module.c#L745](https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/blob/master/ngx_rtmp_notify_module.c#L745)

Or is this not what you mean?

**Comment by misiek08** [comment]
This module send clientid to the specified URL, so you can listen to
on_play, on_publish and on_update and from first two just remember client
state.  It's workaround, but works.

**Comment by ryr** [comment]
>you should get one of the two call queries

users can fake queries and as in https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/issues/97 i cant prevent it

**Comment by ryr** [comment]
same with clientid's - it's querie param wich can be faked

**Comment by misiek08** [comment]
Are you sure clientid can be faked? Please check it, I'll look into it too.
I think client is able to fake only connection parameters like tcurl,
pageurl, swfurl and similar.

**Comment by ryr** [comment]
already checked. with
``rtmp://localhost/live&streamname?flashver=fake&call=update_fake&swfurl=fake&pageurl=http://fake.com&clientid=fake
``
on_play event send post data with this faked params, but in rtmp config i can get unmodified (real) params. i dont understand why events change them.

**Comment by sergey-dryabzhinsky** [comment]
Oh! What because nginx-rtmp don't check if its internal http-request arguments already present in custom client arguments.
How request formed:
- create memory chunk for request data
- nginx-rtmp put internal args into it (by string formating)
- add client arguments stored in session or/and from config url
- formating request - where things zippped, only last one argument definition stay alive

What should we do?
- nginx-rtmp internal arguments are stronger priority by default?
- or we need special option for nginx-rtmp to override client params with internal?

**Comment by ryr** [comment]
>nginx-rtmp internal arguments are stronger priority by default?
i think this one is enough. I do not know the reason for which client would need to change internal args

**Comment by misiek08** [comment]
Already existing parameters should have priority, because internal data is
most important. It's interesting this issue wasn't discovered earlier...

**Comment by sergey-dryabzhinsky** [comment]
Ok. I'll check soon how reordered params setup works.
If all ok - this issue need to be adressed to @arut as well.

**Comment by sergey-dryabzhinsky** [comment]
Please try ```notify-reorder-internal-params-setup``` branch code.

**Comment by ryr** [comment]
>It's interesting this issue wasn't discovered earlier...

This is exactly what I wanted in https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/issues/97 :)

**Comment by ryr** [comment]
notify-reorder-internal-params-setup branch is not working for me.

`master` branch post data:
```
Array
(
    [app] => live
    [flashver] => fake
    [swfurl] => fake
    [tcurl] => rtmp://127.0.0.1/live
    [pageurl] => http://fake.com
    [addr] => 127.0.0.1
    [clientid] => fake
    [call] => update_fake
    [name] => ryr
    [start] => 0
    [duration] => 0
    [reset] => 0
    [sid] => fgtb8lool0t9eq6u29f95omcu2
)
```
`notify-reorder-internal-params-setup` branch post data:
```
Array
(
    [app] => live
    [flashver] => fake
    [swfurl] => fake
    [tcurl] => rtmp://127.0.0.1/live
    [pageurl] => http://fake.com
    [addr] => 127.0.0.1
    [clientid] => fake
    [call] => play
    [name] => ryr
    [start] => 0
    [duration] => 0
    [reset] => 0
)
```
only `call` arg is what i want now, but my additional params are lost (`sid` is missing)

**Comment by sergey-dryabzhinsky** [comment]
Hm. I'll check this.

**Comment by sergey-dryabzhinsky** [comment]
@ryr Are you sure you are using latest code from branch?
How do you connect, play? What your nginx config option for notify handlers?

This is my results by simple test: ffmpeg push stream (screen grab), ffprobe check stream.
- ffprobe: ```ffprobe "rtmp://localhost/rtmp?call=fake playpath=live?call=fake2&sid=123456 live=1"```
- results in php - json encode $_POST:
  - on_connect: ```{"call":"connect","app":"rtmp","flashver":"","swfurl":"","tcurl":"rtmp:\\/\\/localhost\\/rtmp?call=fake","pageurl":"","addr":"1
27.0.0.1","epoch":"937867212"}```
  - on_play: ```{"app":"rtmp","flashver":"","swfurl":"","tcurl":"rtmp:\\/\\/localhost\\/rtmp?call=fake","pageurl":"","addr":"127.0.0.1","client
id":"12call=fake2","sid":"123456","call":"play","name":"live","start":"4294966296","duration":"0","reset":"0"}```

**Comment by ryr** [comment]
nginx rtmp conf:
```
	application live {
		live on;

		on_play http://localhost:8080/check;

		notify_update_timeout 5s;
		on_update http://localhost:8080/check2;

		allow publish 127.0.0.1;
		deny publish all;
		allow play all;
	}
```
url in browser:
```
rtmp://127.0.0.1/live&streamname?sid=fgtb8lool0t9eq6u29f95omcu2&flashver=fake&call=update_fake&swfurl=fakeurl&pageurl=http://fake.com&clientid=fakeid
```

**Comment by sergey-dryabzhinsky** [comment]
Eh? You got application name = 'live&streamname'. You should pull 'rtmp://127.0.0.1/live/streamname?sid=...'

**Comment by ryr** [comment]
nginx debug log for your variant:
```
2016/04/21 14:59:53 [info] 5853#5853: *12 connect: app='live/ryr' args='sid=lpkl8ck98mq78lkbgpr7qnhbs1&flashver=fake&call=update_fake&swfurl=fakeurl&pageurl=http:/' flashver='LNX 11,2,202,616' swf_url='http://vjs.zencdn.net/swf/5.0.1/video-js.swf' tc_url='rtmp://127.0.0.1/live/ryr?sid=lpkl8ck98mq78lkbgpr7qnhbs1&flashver=fake&call=update_fake&swfurl=fakeurl&pageurl=http://' page_url='http://chat.ru/@ryr' acodecs=3575 vcodecs=252 object_encoding=3, client: 127.0.0.1, server: 0.0.0.0:1935
```
my variant works:
```
2016/04/21 15:03:43 [info] 5853#5853: *15 connect: app='live' args='' flashver='LNX 11,2,202,616' swf_url='http://vjs.zencdn.net/swf/5.0.1/video-js.swf' tc_url='rtmp://127.0.0.1/live' page_url='http://chat.ru/@ryr' acodecs=3575 vcodecs=252 object_encoding=3, client: 127.0.0.1, server: 0.0.0.0:1935
2016/04/21 15:03:43 [info] 5853#5853: *15 play: name='ryr' args='sid=lpkl8ck98mq78lkbgpr7qnhbs1&flashver=fake&call=update_fake&swfurl=fakeurl&pageurl=http://fake.com&clientid=fakeid' start=0 duration=0 reset=0 silent=0, client: 127.0.0.1, server: 0.0.0.0:1935

```

**Comment by ryr** [comment]
access log for my variant:
```
127.0.0.1 [21/Apr/2016:15:23:37 +0600] PLAY "live" "ryr" "sid=lpkl8ck98mq78lkbgpr7qnhbs1&flashver=fake&call=update_fake&swfurl=fakeurl&pageurl=http://fake.com&clientid=fakeid" - 552 491 "http://chat.ru/@ryr" "LNX 11,2,202,616" (0s)
```

**Comment by sergey-dryabzhinsky** [comment]
Ok, connection string depends on client.
What about POST data which arrives via on_connect / on_play / on_update handler?
- on_update: ```{"app":"rtmp","flashver":"","swfurl":"","tcurl":"rtmp:\\/\\/localhost\\/rtmp?call=fake","pageurl":"","addr":"127.0.0.1","clientid":"17call=fake2","sid":"123456","call":"update_play","time":"10","timestamp":"28000","name":"live"}```

**Comment by ryr** [comment]
https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/issues/98#issuecomment-212766941

**Comment by sergey-dryabzhinsky** [comment]
Found possible logic bug.

**Comment by sergey-dryabzhinsky** [comment]
@ryr please try latest code from branch

**Comment by ryr** [comment]
Unfortunately the result is the same as the previous time, except now there is clients params.

p.s. got warnings during install:
```
ngx_rtmp_notify_module.c: In function ‘ngx_rtmp_notify_connect_create’:
ngx_rtmp_notify_module.c:387:62: error: unused variable ‘page_url_len’ [-Werror=unused-variable]
                                     swf_url_len, tc_url_len, page_url_len;
                                                              ^
ngx_rtmp_notify_module.c:387:50: error: unused variable ‘tc_url_len’ [-Werror=unused-variable]
                                     swf_url_len, tc_url_len, page_url_len;
                                                  ^
ngx_rtmp_notify_module.c:387:37: error: unused variable ‘swf_url_len’ [-Werror=unused-variable]
                                     swf_url_len, tc_url_len, page_url_len;
                                     ^
ngx_rtmp_notify_module.c:386:56: error: unused variable ‘flashver_len’ [-Werror=unused-variable]
     size_t                          app_len, args_len, flashver_len,
                                                        ^
ngx_rtmp_notify_module.c:386:37: error: unused variable ‘app_len’ [-Werror=unused-variable]
     size_t                          app_len, args_len, flashver_len,
                                     ^
ngx_rtmp_notify_module.c:385:37: error: unused variable ‘addr_text’ [-Werror=unused-variable]
     ngx_str_t                      *addr_text;
                                     ^
```

**Comment by sergey-dryabzhinsky** [comment]
Can you again:
1. try latest code from branch
2. show RAW POST data - like read whole ```php://input``` by ```on_play``` / ```on_update``` url handler

**Comment by sergey-dryabzhinsky** [comment]
Got it. Request params got overrided again and again.
I'll try again fix that logic.

**Comment by sergey-dryabzhinsky** [comment]
@ryr Try latest code from branch again please. I hope it works now.

**Comment by ryr** [comment]
it works!

**Comment by sergey-dryabzhinsky** [comment]
Merged into master.
